### ISSUE TITLE
Unable to buy residence under certain circumstances

### ISSUE THREAD

**Issue by IzaacJ** [Zrips/Residence#1015]
PaperMC: git-Paper-447
Residence: 5.1.1.1
CMILib: 1.2.4.6
SEconomy: 0.0.45-SNAPSHOT
ObsidianMC: 0.1.25
Vault: 1.7.3
LuckPerms: 5.4.40
WorldGuard: 7.0.8
WorldEdit: 7.2.13
Geyser: 2.1.0
Floodgate: 2.2.2

When buying a residence ~owned by a player that is offline~ I sometimes get the stacktrace below.
From my limited testing using 3 accounts it happens if the owner is either offline, or Server_Land is the owner.

```
[21:28:53 ERROR]: Could not pass event PlayerInteractEvent to Residence v5.1.1.1
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v5.1.1.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.3.jar:git-Paper-447]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:980) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onSignInteract(ResidencePlayerListener.java:730) ~[Residence5.1.1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor265.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-447]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-447]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-447]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:528) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-447]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.OfflinePlayer.getUniqueId()" because "player" is null
        at fr.stormer3428.economy.SEconomy.depositPlayer(SEconomy.java:203) ~[StormerEconomy-0.0.45-SNAPSHOT.jar:?]
        at fr.stormer3428.economy.SEconomy.depositPlayer(SEconomy.java:197) ~[StormerEconomy-0.0.45-SNAPSHOT.jar:?]
        at com.bekvon.bukkit.residence.vaultinterface.ResidenceVaultAdapter.transfer(ResidenceVaultAdapter.java:133) ~[Residence5.1.1.1.jar:?]
        at com.bekvon.bukkit.residence.economy.TransactionManager.buyPlot(TransactionManager.java:237) ~[Residence5.1.1.1.jar:?]
        at com.bekvon.bukkit.residence.commands.market.perform(market.java:203) ~[Residence5.1.1.1.jar:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence5.1.1.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 30 more
```

Note: as a sidenote, I have to run `/resreload` after a server restart to get Residence to recognize SEconomy, since Residence gets loaded between Vault and SEconomy. Is there something I can do about that?

**Comment by Zrips** [comment]
Error is from your economy plugin failing to transfer money, not much I can do here. You will need to get into contact with SEconomy dev or use more up to date plugin for your purposes.
