### ISSUE TITLE
server crashes when players use command res expand

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#1017]
When a player use the command res expand,
the console shows the error and the server crashes.
Purpur verison: 1.19.2(1858)
Residence version: v5.1.1.1
CMILib verison: 1.2.5.2

[19:15:24] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to Residence v5.1.1.1
java.lang.StackOverflowError: null
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:693) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1325) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1232) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1227) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:551) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.teleport(ResidencePlayerListener.java:2261) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.handleNewLocation(ResidencePlayerListener.java:2538) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerTeleport(ResidencePlayerListener.java:1885) ~[Residence5.1.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor874.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1325) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1232) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1227) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:551) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.teleport(ResidencePlayerListener.java:2261) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.handleNewLocation(ResidencePlayerListener.java:2538) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerTeleport(ResidencePlayerListener.java:1885) ~[Residence5.1.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor874.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1325) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1232) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1227) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:551) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.teleport(ResidencePlayerListener.java:2261) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.handleNewLocation(ResidencePlayerListener.java:2538) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerTeleport(ResidencePlayerListener.java:1885) ~[Residence5.1.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor874.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]

**Comment by xyfwdy** [comment]
same

**Comment by Zrips** [comment]
2a6ccb2823cbb944d126480587ce2b53f0b54e0e
