### ISSUE TITLE
invalid color nukes residences when saving

### ISSUE THREAD

**Issue by dan28000** [Zrips/Residence#1033]
when having wrong ResidenceChatColor in config it results to nuking all residences when saving

happend to me on testing server having LIGHT_BLUE instead of  LIGHT BLUE

java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Colors.CMIChatColor.getName()" because the return value of "com.bekvon.bukkit.residence.ConfigManager.getChatColor()" is null
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.save(ClaimedResidence.java:1631) ~[Residence5.1.1.2.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.save(ResidenceManager.java:928) ~[Residence5.1.1.2.jar:?]
	at com.bekvon.bukkit.residence.Residence.saveYml(Residence.java:1291) ~[Residence5.1.1.2.jar:?]
	at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:424) ~[Residence5.1.1.2.jar:?]

**Comment by Zrips** [comment]
e89686a37dbe322e4ed31d41d92f08816f52007d
