### ISSUE TITLE
[1.12.2]error message : Could not pass event ProjectileHitEvent

### ISSUE THREAD

**Issue by LittleKing2004** [Zrips/Residence#1036]
Error Message
---------------------------------------------------------------------------------------------------------------------------------------------
[Server thread/ERROR]: Could not pass event ProjectileHitEvent to Residence v5.1.1.3
java.lang.NoSuchMethodError: org.bukkit.event.entity.ProjectileHitEvent.getHitBlockFace()Lorg/bukkit/block/BlockFace;
        at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.onAnvilInventoryClick(ResidenceBlockListener.java:103) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor454.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:893) [CraftEventFactory.class:git-CatServer-1.12.2-fed56812]
        at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:252) [aev.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2311) [amu.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2265) [amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2029) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:978) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
---------------------------------------------------------------------------------------------------------------------------------------------
Description:
  Whenever I throw out the potion bottle, this error message is displayed , only this one.

Plugin version : 5.1.1.3
Server version: 1.12.2
server core: CatServer-fed56812-universal.jar
           link: https://catmc.org/

**Comment by Zrips** [comment]
168f2193624900f1e2774e73e0978c9ce5eeff4a
