### ISSUE TITLE
CMI Incompatible

### ISSUE THREAD

**Issue by MidianIdu** [Zrips/Residence#1043]
[21:40:57] [Server thread/INFO]: Midian issued server command: /res set
[21:41:01] [Server thread/INFO]: Midian issued server command: /resadmin set
[21:41:01] [Server thread/ERROR]: Cannot load plugins\CMILib\Translations\Locale_EN.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed
in "'reader'", position 0
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.Zrips.CMILib.Locale.YmlMaker.reloadConfig(YmlMaker.java:41) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Locale.YmlMaker.getConfig(YmlMaker.java:58) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Locale.Language.reload(Language.java:42) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.CMILib.getLM(CMILib.java:86) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Messages.CMIMessages.getMsg(CMIMessages.java:202) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Locale.LC.getLocale(LC.java:484) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.GUI.CMIGui.addPagination(CMIGui.java:458) ~[CMILib1.3.0.0.jar:?]
	at com.bekvon.bukkit.residence.gui.FlagUtil.openUI(FlagUtil.java:104) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.gui.FlagUtil.openSetFlagGui(FlagUtil.java:117) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.commands.set.perform(set.java:67) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence5.1.1.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.19.4.jar:git-Paper-538]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-538]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 38 more
[21:41:01] [Server thread/ERROR]: Cannot load plugins\CMILib\Translations\Locale_EN.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed
in "'reader'", position 0
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.Zrips.CMILib.Locale.YmlMaker.reloadConfig(YmlMaker.java:41) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Locale.YmlMaker.getConfig(YmlMaker.java:58) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Locale.Language.getEN(Language.java:51) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Locale.Language.isList(Language.java:519) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Messages.CMIMessages.getMsg(CMIMessages.java:202) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.Locale.LC.getLocale(LC.java:484) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.GUI.CMIGui.addPagination(CMIGui.java:458) ~[CMILib1.3.0.0.jar:?]
	at com.bekvon.bukkit.residence.gui.FlagUtil.openUI(FlagUtil.java:104) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.gui.FlagUtil.openSetFlagGui(FlagUtil.java:117) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.commands.set.perform(set.java:67) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence5.1.1.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.19.4.jar:git-Paper-538]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-538]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 38 more
[21:41:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'resadmin' in plugin Residence v5.1.1.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.19.4.jar:git-Paper-538]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-538]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-538]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Items.CMIItemStack.getItemStack()" because the return value of "net.Zrips.CMILib.CMILibConfig.getGUIEmptyField()" is null
	at net.Zrips.CMILib.GUI.CMIGui.addEmptyButton(CMIGui.java:328) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.GUI.CMIGui.fillEmptyButtons(CMIGui.java:303) ~[CMILib1.3.0.0.jar:?]
	at net.Zrips.CMILib.GUI.CMIGui.fillEmptyButtons(CMIGui.java:295) ~[CMILib1.3.0.0.jar:?]
	at com.bekvon.bukkit.residence.gui.FlagUtil.openUI(FlagUtil.java:106) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.gui.FlagUtil.openSetFlagGui(FlagUtil.java:117) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.commands.set.perform(set.java:67) ~[Residence5.1.1.3.jar:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence5.1.1.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 23 more

**Comment by Zrips** [comment]
Looks to be issues with your CMILib setup, quickest fix would be to rename CMILib folder and let it regenerate which should put default working values.
