### ISSUE TITLE
 16/5000 翻译 Request to have him repaired. I can't see all the territory

### ISSUE THREAD

**Issue by aml2023529** [Zrips/Residence#1045]
> res list
[22:01:03 WARN]: Unexpected exception while parsing console command "res list"
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v5.1.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:933) ~[paper-1.20.1.jar:git-Paper-36]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:896) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-36]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.IllegalArgumentException: UUID id cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-36]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:720) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.bekvon.bukkit.residence.containers.ResidencePlayer.updatePlayer(ResidencePlayer.java:299) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.containers.ResidencePlayer.getName(ResidencePlayer.java:379) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.addPlayer(PlayerManager.java:36) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.playerJoin(PlayerManager.java:78) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.getResidencePlayer(PlayerManager.java:306) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.getResidencesMap(PlayerManager.java:187) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.listResidences(ResidenceManager.java:355) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.commands.list.perform(list.java:47) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[[领地]Residence5.1.1.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
> resadmin list
[22:01:20 WARN]: Unexpected exception while parsing console command "resadmin list"
org.bukkit.command.CommandException: Unhandled exception executing command 'resadmin' in plugin Residence v5.1.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:933) ~[paper-1.20.1.jar:git-Paper-36]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:896) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-36]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.IllegalArgumentException: UUID id cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-36]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:720) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.bekvon.bukkit.residence.containers.ResidencePlayer.updatePlayer(ResidencePlayer.java:299) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.containers.ResidencePlayer.getName(ResidencePlayer.java:379) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.addPlayer(PlayerManager.java:36) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.playerJoin(PlayerManager.java:78) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.getResidencePlayer(PlayerManager.java:306) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.PlayerManager.getResidencesMap(PlayerManager.java:187) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.listResidences(ResidenceManager.java:355) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.commands.list.perform(list.java:47) ~[[领地]Residence5.1.1.3.jar:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[[领地]Residence5.1.1.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
>

**Comment by Zrips** [comment]
a7962c867d0042a038c5bef9f7fbea161659b347
Keep in mind that while performing command **/res list** from console you will need to provide players name, like for example **/res list Zrips**
If you want to list all residences on entire server then use **/res listall**
