### ISSUE TITLE
cannot load after update to the lastest version

### ISSUE THREAD

**Issue by Chenyu550** [Zrips/Residence#1056]
`[10:54:48 ERROR]: Error occurred while enabling Residence v5.1.2.0 (Is it up to date?)`
java.lang.NoSuchFieldError: BRUSH
        at com.bekvon.bukkit.residence.containers.Flags.<clinit>(Flags.java:26) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.ConfigManager.loadFlags(ConfigManager.java:1543) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:347) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1112) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:495) ~[Residence5.1.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:54:48 INFO]: [Residence] Disabling Residence v5.1.2.0
`[10:54:48 ERROR]: Error occurred while disabling Residence v5.1.2.0 (Is it up to date?)`
java.lang.NoClassDefFoundError: Could not initialize class com.bekvon.bukkit.residence.containers.Flags
        at com.bekvon.bukkit.residence.ConfigManager.loadFlags(ConfigManager.java:1543) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:347) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1112) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager.readConfig(PermissionManager.java:165) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager.<init>(PermissionManager.java:58) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.Residence.getPermissionManager(Residence.java:1053) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:404) ~[Residence5.1.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by cool9850311** [comment]
i got the same issue, just update cmilib to latest ver, then it will get fixed

**Comment by Zrips** [comment]
@Chenyu550 
Always try to keep CMILib at latest version when you update relating plugins to it.
