### ISSUE TITLE
The plugin can no longer be used in 1.20.1..

### ISSUE THREAD

**Issue by wn0614** [Zrips/Residence#1063]
The plugin can no longer be used in 1.20.1..

- [ 14:34:10 ERROR Minecraft] null
org.bukkit.command.CommandException: Cannot execute command 'res' in plugin Residence v5.1.2.0 - plugin is disabled.
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003)
    at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
    at net.minecraft.commands.Commands.performCommand(Commands.java:324)
    at net.minecraft.commands.Commands.performCommand(Commands.java:308)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259)
    at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316)
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309)
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.

**Comment by Zrips** [comment]
Error like this usually happens when plugin fails to load in general, which usually gets caused by faulty config/save files. Without actual error log from startup can't say what exactly went wrong here.

**Comment by Zernca** [comment]
same

**Comment by Zernca** [comment]
[7:30:51 PM INFO]: L1qu1dB0unc3 issued server command: /res
[7:30:51 PM ERROR]: Command exception: /res
org.bukkit.command.CommandException: Cannot execute command 'res' in plugin Residence v2.6.6.6 - plugin is disabled.
