### ISSUE TITLE
Residence v5.1.2.0 ERROR : ResidenceFlagCheckEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by aesopcmc** [Zrips/Residence#1066]
Residence Version: Residence v5.1.2.0 
Paper Version: 1.19.3
Slimefun4 ext:  Networks-Build 79 zh-CN(ybw0014) (git 3a763e9).jar

info: 
[14:33:55 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.1.2.0"
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:660) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:127) ~[Residence5.1.2.0.jar:?]
        at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:48) ~[Residence5.1.2.0.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun-v2023.06-release.jar:?]
        at io.github.sefiraat.networks.slimefun.tools.NetworkRemote$1.onResult(NetworkRemote.java:114) ~[[粘液科技扩展-网络]Networks-Build 79 zh-CN(ybw0014) (git 3a763e9).jar:?]
        at io.github.sefiraat.networks.slimefun.tools.NetworkRemote$1.onResult(NetworkRemote.java:106) ~[[粘液科技扩展-网络]Networks-Build 79 zh-CN(ybw0014) (git 3a763e9).jar:?]
        at com.xzavier0722.mc.plugin.slimefun4.storage.controller.ADataController.lambda$invokeCallback$2(ADataController.java:124) ~[Slimefun-v2023.06-release.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by aesopcmc** [comment]
> what version of slimefun is this? Slimefun-v2023.06-release.jar Update: I got the error too https://pastebin.com/JS5ge5eG
no office version: 
https://github.com/StarWishsama/Slimefun4

**Comment by Zrips** [comment]
Issue with your network addon for slimefun, its calling permission check async which isn't happening in normal use case with basic slime fun plugin which calls it properly on sync. This needs to be fixed from networks plugin side.
