### ISSUE TITLE
Still get error messages when player teleport

### ISSUE THREAD

**Issue by xyfwdy** [Zrips/Residence#1087]
CMILib version 1.4.1.0
Residence version 5.1.3.0

This server is running Folia version git-Folia-"f6e91e9" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6e91e9)
You are running the latest version
Previous version: git-Folia-"3cf16ee" (MC: 1.20.1)

```
[05:29:48] [Region Scheduler Thread #0/INFO]: haohao issued server command: /res tp dlkkt
[05:29:48] [Region Scheduler Thread #0/ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkSource.getChunk(ChunkSource.java:12) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.getChunkAt(CraftWorld.java:336) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.getChunkAt(CraftWorld.java:965) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at org.bukkit.Location.getChunk(Location.java:123) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.performInstantTp(ClaimedResidence.java:1546) ~[Residence5.1.3.0.jar:?]
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.tpToResidence(ClaimedResidence.java:1500) ~[Residence5.1.3.0.jar:?]
	at com.bekvon.bukkit.residence.commands.tp.perform(tp.java:47) ~[Residence5.1.3.0.jar:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence5.1.3.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1048) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2378) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2338) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by Zrips** [comment]
f1f1cb652ddda390a6a7fa0a9eeda06b4aee72e3
