### ISSUE TITLE
NoSuchFieldError: CAKE

### ISSUE THREAD

**Issue by xlinuxmanx** [Zrips/Residence#1093]
Unable to load the plugin. Using PaperMC 1.20.1 build 132, CMILib installed, turned off the flag cake in the config and still receiving this error.

```
[21:41:27 ERROR]: Error occurred while enabling Residence v5.1.3.0 (Is it up to date?)
java.lang.NoSuchFieldError: CAKE
	at com.bekvon.bukkit.residence.protection.FlagPermissions.initValidFlags(FlagPermissions.java:242) ~[Residence5.1.3.0.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:700) ~[Residence5.1.3.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-132]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-132]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Zrips** [comment]
Update your CMILib and it should resolve your issue.
