### ISSUE TITLE
When using /res tp, an error is reported on folia

### ISSUE THREAD

**Issue by postyizhan** [Zrips/Residence#1096]
```
[08:45:37 INFO]: 12121 issued server command: /res tp 2
[08:45:37 ERROR]: Thread Region Scheduler Thread #5 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[folia-1.20.1.jar:git-Folia-13]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
        at net.minecraft.world.level.Level.getBlockState(Level.java:821) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[folia-1.20.1.jar:git-Folia-13]
        at net.Zrips.CMILib.Items.CMIMaterial.get(CMIMaterial.java:1862) ~[CMILib1.4.1.0.jar:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.isEmptyBlock(ResidencePlayerListener.java:1040) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.protection.ClaimedResidence.isSafeTp(ClaimedResidence.java:1409) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.protection.ClaimedResidence.tpToResidence(ClaimedResidence.java:1462) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.commands.tp.perform(tp.java:47) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1044) ~[folia-1.20.1.jar:git-Folia-13]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-13]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2326) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2286) ~[?
:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-13]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-13]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Fol
ia-13]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.ja
r:git-Folia-13]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar
:git-Folia-13]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:45:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v5.1.2.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1044) ~[folia-1.20.1.jar:git-Folia-13]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-13]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2326) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2286) ~[?
:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-13]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-13]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Fol
ia-13]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.ja
r:git-Folia-13]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar
:git-Folia-13]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Scheduling chunk load off-main
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[folia-1.20.1.jar:git-Folia-13]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
        at net.minecraft.world.level.Level.getBlockState(Level.java:821) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[folia-1.20.1.jar:git-Folia-13]
        at net.Zrips.CMILib.Items.CMIMaterial.get(CMIMaterial.java:1862) ~[CMILib1.4.1.0.jar:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.isEmptyBlock(ResidencePlayerListener.java:1040) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.protection.ClaimedResidence.isSafeTp(ClaimedResidence.java:1409) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.protection.ClaimedResidence.tpToResidence(ClaimedResidence.java:1462) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.commands.tp.perform(tp.java:47) ~[Residence.jar:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 14 more
```

**Comment by cgw2023** [comment]
same as #1087

**Comment by Zrips** [comment]
f1f1cb652ddda390a6a7fa0a9eeda06b4aee72e3

**Comment by KLWarGod** [comment]
@Zrips This issue still exists in the latest version. I found that coordinates that are closer to each other can be transmitted, while those that are farther away report an error (sorry, the translation used):
[2023-10-18-6.log](https://github.com/Zrips/Residence/files/13013185/2023-10-18-6.log)
