### ISSUE TITLE
FAILED INITIALIZATION! DISABLED!

### ISSUE THREAD

**Issue by abc110210** [Zrips/Residence#1101]
[19:03:32 ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "this.item" is null
        at net.Zrips.CMILib.Items.CMIItemStack.getItemStack(CMIItemStack.java:394) ~[CMILib1.4.1.0.jar:?]
        at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:66) ~[Residence5.1.3.0.jar:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:508) ~[Residence5.1.3.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.1.jar:git-Folia-17]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

folia-1.20
java17

**Comment by Zrips** [comment]
Double check your flags.yml file and specifically FlagGui section, from your error it looks like there is incorrect material type defined which causes this issue, will fix it with next update, but you can make a quick fix by resolving incorrect material name or just remove entire section and let it regenerate to default values.
