### ISSUE TITLE
Cannot getEntities asynchronously on Folia

### ISSUE THREAD

**Issue by jason920612** [Zrips/Residence#1103]
[10:20:02 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Cannot getEntities asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:85) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.world.level.Level.getEntities(Level.java:1153) ~[?:?]
        at net.minecraft.world.level.EntityGetter.getEntities(EntityGetter.java:50) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:588) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3016) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:855) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:393) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:633) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:480) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1528) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:20:02 WARN]: [io.papermc.paper.threadedregions.RegionizedWorldData] Failed to handle packet for /***.***.**.***:29097
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:941) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:393) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:633) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:480) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1528) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot getEntities asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:86) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.world.level.Level.getEntities(Level.java:1153) ~[?:?]
        at net.minecraft.world.level.EntityGetter.getEntities(EntityGetter.java:50) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:588) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3016) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:855) ~[?:?]
        ... 8 more

**Comment by Zrips** [comment]
Error message doesn't mention residence plugin or CMIlib. it does mention **ca.spottedleaf** which looks more like a plugin which caused this error.
