### ISSUE TITLE
Circular plugin loading detected!

### ISSUE THREAD

**Issue by Mi4i19** [Zrips/Residence#1144]
[13:48:50 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[13:48:50 ERROR]: [SimpleProviderStorage] Circular load order:
[13:48:50 ERROR]: [SimpleProviderStorage]   Residence -> CMI -> DiscordSRV -> Skript -> Residence
[13:48:50 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[13:48:50 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[13:48:50 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins Residence
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[purpur-1.20.1.jar:git-Purpur-2016]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[purpur-1.20.1.jar:git-Purpur-2016]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2016]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.1.jar:git-Purpur-2016]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2016]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2016]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2016]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[13:48:50 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2024-02-08_13.48.50-server.txt

**Comment by Zrips** [comment]
Update CMI plugin which should no longer have soft dependency for DiscordSRV and fix this issue for you
