### ISSUE TITLE
[ERROR] Can't Work

### ISSUE THREAD

**Issue by 849025143** [Zrips/Residence#1157]
Server: CatServer-1.12.2
plugin: 5.1.4.3 and 5.1.4.0

[09:07:53] [Server thread/ERROR]: Error occurred while enabling Residence v5.1.4.0 (Is it up to date?)
java.lang.NoSuchFieldError: BRUSH
        at com.bekvon.bukkit.residence.containers.Flags.<clinit>(Flags.java:26) ~[?:?]
        at com.bekvon.bukkit.residence.ConfigManager.loadFlags(ConfigManager.java:1551) ~[?:?]
        at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:349) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1112) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:498) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-fed56812]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]

**Comment by Zrips** [comment]
Updating to latest CMILib should have solved this issue
