### ISSUE TITLE
Spigot 1.20.6 Residence + CMILib Error on Server StartUp

### ISSUE THREAD

**Issue by AmkSoft** [Zrips/Residence#1170]
`
[18:06:26] [Server thread/INFO]: [CMILib] Enabling CMILib v1.4.7.4
[18:06:28] [Server thread/INFO]: Server version: v1_20_R4 - 1.20.6 - spigot  4142-Spigot-e2c1eee-0364df4 (MC: 1.20.6)
[18:06:29] [Server thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:06:29] [Server thread/INFO]: Updated (EN) language file. Took 96ms

[18:06:42] [Server thread/INFO]: [Residence] Enabling Residence v5.1.4.3
[18:06:42] [Server thread/INFO]: Can't find effect for Selected Sides with this name, it was set to default
[18:06:42] [Server thread/INFO]: Send: Error occurred while enabling Residence v5.1.4.3 (Is it up to date?)
[18:06:42] [Server thread/ERROR]: Error occurred while enabling Residence v5.1.4.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/Zrips/CMI/CMI
        at net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.getKey(CMIPersistentDataContainer.java:53) ~[?:?]
        at net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.hasKey(CMIPersistentDataContainer.java:59) ~[?:?]
        at net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:1275) ~[?:?]
        at net.Zrips.CMILib.Items.CMIItemStack.getEntityType(CMIItemStack.java:594) ~[?:?]
        at net.Zrips.CMILib.Items.CMIItemStack.setEnt(CMIItemStack.java:337) ~[?:?]
        at net.Zrips.CMILib.Items.CMIItemStack.getItemStack(CMIItemStack.java:364) ~[?:?]
        at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:64) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:512) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4142-Spigot-e2c1eee-0364df4]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4142-Spigot-e2c1eee-0364df4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4142-Spigot-e2c1eee-0364df4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4142-Spigot-e2c1eee-0364df4]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4142-Spigot-e2c1eee-0364df4]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4142-Spigot-e2c1eee-0364df4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4142-Spigot-e2c1eee-0364df4]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.CMI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 19 more

`
What can be wrong?, It worked perfect on Spigot 1.20.4, but after upgrade its not working.

**Comment by TekuSP** [comment]
Same problem

**Comment by Barzza1999** [comment]
Same problem

**Comment by Zrips** [comment]
Will be resolved with next CMILib update which should come out today
