### ISSUE TITLE
IllegalArgumentException: object is not an instance of declaring class

### ISSUE THREAD

**Issue by mxlt02** [Zrips/Residence#1188]
[12:04:49 WARN]: java.lang.IllegalArgumentException: object is not an instance of declaring class
[12:04:49 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197)
[12:04:49 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99)
[12:04:49 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[12:04:49 WARN]:        at Residence5.1.5.0.jar//com.bekvon.bukkit.residence.allNms.v1_9Events.onLingeringEffectApply(v1_9Events.java:84)
[12:04:49 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1022.execute(Unknown Source)
[12:04:49 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[12:04:49 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[12:04:49 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:04:49 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[12:04:49 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:04:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[12:04:49 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callAreaEffectCloudApplyEvent(CraftEventFactory.java:1834)
[12:04:49 WARN]:        at net.minecraft.world.entity.EntityAreaEffectCloud.l(EntityAreaEffectCloud.java:298)
[12:04:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1409)
[12:04:49 WARN]:        at net.minecraft.world.level.World.a(World.java:1318)
[12:04:49 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$8(WorldServer.java:916)
[12:04:49 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[12:04:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:896)
[12:04:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1724)
[12:04:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[12:04:49 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1525)
[12:04:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[12:04:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:04:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

paper1.20.4 Residence5.1.5.0

**Comment by 4L0N50asd** [comment]
x2 That's happening to me too, every time an entity takes damage from a lingering potion (this includes the area damage effect that generates the dragon fireball), i got the same error

Using Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
Residence version 5.1.5.0

**Comment by Zrips** [comment]
60390337529938870d5ae0aec427737a2e56eb6e
