### ISSUE TITLE
[!] Infinity errors on 5.1.5.2 - PotionEffectType WEAVING

### ISSUE THREAD

**Issue by smscentras** [Zrips/Residence#1194]
`[02:44:22 ERROR]: Could not pass event EntityDeathEvent to Residence v5.1.5.2
java.lang.NoSuchFieldError: Class org.bukkit.potion.PotionEffectType does not have member field 'org.bukkit.potion.PotionEffectType WEAVING'
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener1_20.OnEntityDeath(ResidencePlayerListener1_20.java:100) ~[Residence5.1.5.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor601.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:996) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1909) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1801) ~[?:?]
        at net.minecraft.world.entity.animal.IronGolem.die(IronGolem.java:368) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1613) ~[?:?]
        at net.minecraft.world.entity.animal.IronGolem.hurt(IronGolem.java:263) ~[?:?]
        at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:990) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:912) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:412) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:370) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:852) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3116) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:463) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1492) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:940) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:917) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by mercurialmusic** [comment]
Confirming the same, massive spam on any entity death. Running git-Paper-497 (MC: 1.20.4) with Residence 5.1.5.2 and CMILib 1.5.0.8.

**Comment by Therealalex1s** [comment]
Confirming the same, massive spam on any entity death. Running git-Paper-497 (MC: 1.20.4) with Residence 5.1.5.2 and CMILib 1.5.0.9.

**Comment by Zrips** [comment]
Should be resolved with new version
