### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent/ProjectileLaunchEvent to Residence v5.1.5.2

### ISSUE THREAD

**Issue by snowykami** [Zrips/Residence#1198]
After I update the Server to paper 1.20.1(latest build of 1.20.1 196)

**Server Paper-1.20.1 build 196**
**Start Args: -Xmx40G -Xms40G -XX:+UseZGC**
**Java: OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)**

Error
```log
Could not pass event EntityDamageByEntityEvent to Residence v5.1.5.2
Could not pass event ProjectileLaunchEvent to Residence v5.1.5.2
```

```log
[20:42:16 ERROR]: Could not pass event ProjectileLaunchEvent to Residence v5.1.5.2
java.lang.NoSuchMethodError: 'net.Zrips.CMILib.Entities.CMIEntityType net.Zrips.CMILib.Entities.CMIEntityType.get(org.bukkit.entity.Entity)'
        at com.bekvon.bukkit.residence.listeners.ResidenceEntityListener.onProjectileLaunch(ResidenceEntityListener.java:667) ~[Residence5.1.5.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor364.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1485) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:696) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1656) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1564) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1559) ~[?:?]
        at net.minecraft.world.item.EnderpearlItem.use(EnderpearlItem.java:30) ~[?:?]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:546) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2096) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1385) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]   
```

```log
[20:42:17 ERROR]: Could not pass event EntityDamageByEntityEvent to Residence v5.1.5.2
java.lang.NoSuchMethodError: 'net.Zrips.CMILib.Entities.CMIEntityType net.Zrips.CMILib.Entities.CMIEntityType.get(org.bukkit.entity.EntityType)'
        at com.bekvon.bukkit.residence.listeners.ResidenceEntityListener.onEntityDamageByEntityEvent(ResidenceEntityListener.java:1356) ~[Residence5.1.5.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor392.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1142) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1014) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1249) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2184) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1060) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1431) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:967) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1128) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.onHit(ThrownEnderpearl.java:87) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:194) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:69) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:109) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1352) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1004) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:872) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Plugins Info
```log
[20:50:22 INFO]: Server Plugins (79):
[20:50:22 INFO]: Paper Plugins:
[20:50:22 INFO]:  - FairyChat
[20:50:22 INFO]: Bukkit Plugins:
[20:50:22 INFO]:  - AntiPopup, BetterReactor, BlueMap, ChestCommands, CMIconfigViewer, CMILib, ConfigLib, CoreProtect, CraftEnhance, CrystamaeHistoria
[20:50:22 INFO]:  DankTech2, DynaTech, ElectricSpawners, ElementManipulation, EnchantLimit, ExoticGarden, FasterMinecarts, floodgate, FluffyMachines, Gastronomicon
[20:50:22 INFO]:  Geyser-Spigot, GSit, GuizhanCraft, GuizhanLibPlugin, HeadDisplays, HeadLimiter, HomeGO, HotbarPets, ImageFrame, InfinityExpansion
[20:50:22 INFO]:  Item2Chat, ItemEdit, ItemEditor, *ItemLinker, LagFixer, lightEconomy, LiteXpansion, LuckPerms, mcMMO, MiniBlocks
[20:50:22 INFO]:  MiniMOTD, MobCapturer, NBTAPI, Networks, no-creeper-explosion, NoEncryption, NotEnoughAddons, OpenInv, PlaceholderAPI, PlayerShopGUIPlus
[20:50:22 INFO]:  PluginConstructorAPI, ProtocolLib, QuickShop, RedstoneConnector, Residence, ServerBackup, *SimpleTpa, Slimefun, SlimefunAdvancements, SlimefunOreChunks
[20:50:22 INFO]:  SlimeFunRecipe, SlimefunServerEssentials, SlimeGlue, SlimeHUD, SlimeTinker, spark, Supreme, TAB, *TCExpress, Vault
[20:50:22 INFO]:  VeinMiner, ViaBackwards, ViaRewind, ViaVersion, WkKit, WorldEdit, *XpBottle, ZMusic
```

**Comment by Zrips** [comment]
Updating CMILib resolves issue
