### ISSUE TITLE
ResidenceFlagCheckEvent IllegalStateException

### ISSUE THREAD

**Issue by nate981120** [Zrips/Residence#1201]
[22:53:18 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.1.4.3"
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:156) ~[Residence5.1.4.3.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:74) ~[Residence5.1.4.3.jar:?]
        at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.canBreakBlock(ResidenceBlockListener.java:298) ~[Residence5.1.4.3.jar:?]
        at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:56) ~[Residence5.1.4.3.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:180) ~[Slimefun4 - TEA 286 (git 3a5dc).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:173) ~[Slimefun4 - TEA 286 (git 3a5dc).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkControlX.tryBreakBlock(NetworkControlX.java:127) ~[Networks - EFI 35 (git d35d2).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkControlX.onTick(NetworkControlX.java:70) ~[Networks - EFI 35 (git d35d2).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:102) ~[Networks - EFI 35 (git d35d2).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:184) ~[Slimefun4 - TEA 286 (git 3a5dc).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:171) ~[Slimefun4 - TEA 286 (git 3a5dc).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:141) ~[Slimefun4 - TEA 286 (git 3a5dc).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:110) ~[Slimefun4 - TEA 286 (git 3a5dc).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Zrips** [comment]
3943189ce456315e647dbde0aeb7adc47cafe759
