### ISSUE TITLE
Residence listeners proc by NPC ?!

### ISSUE THREAD

**Issue by Oruss7** [Zrips/Residence#134]
Hello,

I use Citizens and Denizen with Depenizen for Residence support. 
I got error, Depenizen try to catch `onPlayerTeleportEvent` but got an NPC....

```
java.lang.IllegalStateException: NPCs are not allowed as dPlayer objects!
	at net.aufdemrand.denizen.objects.dPlayer.<init>(dPlayer.java:203)
	at com.denizenscript.depenizen.bukkit.events.residence.PlayerEntersResidenceScriptEvent.getScriptEntryData(PlayerEntersResidenceScriptEvent.java:87)
	at net.aufdemrand.denizencore.events.ScriptEvent.run(ScriptEvent.java:260)
	at net.aufdemrand.denizencore.events.ScriptEvent.fire(ScriptEvent.java:240)
	at com.denizenscript.depenizen.bukkit.events.residence.PlayerEntersResidenceScriptEvent.onResidencePlayerEntersResidence(PlayerEntersResidenceScriptEvent.java:105)
	at sun.reflect.GeneratedMethodAccessor293.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerTeleportEvent(ResidencePlayerListener.java:2060)
```

**Comment by Zrips** [comment]
67320103cec19564447369702f76d2f5e05772ac
