### ISSUE TITLE
Bank withdraw error

### ISSUE THREAD

**Issue by xXumarkuXx** [Zrips/Residence#136]
Each time someone tries to withdraw money from there res they get "An internal error occurred while attempting to perform this command" and the deposit command is working perfectly 

Error from console:
`org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.7.5.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at com.massivecraft.massivelag.inject.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:98) ~[MassiveLag.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.IllegalFormatConversionException: d != java.lang.Double
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302) ~[?:1.8.0_111]
at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793) ~[?:1.8.0_111]
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747) ~[?:1.8.0_111]
at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_111]
at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_111]
at java.lang.String.format(String.java:2940) ~[?:1.8.0_111]
at com.bekvon.bukkit.residence.economy.ResidenceBank.withdraw(ResidenceBank.java:81) ~[Residence4.7.5.0.jar:?]
at com.bekvon.bukkit.residence.commands.bank.perform(bank.java:51) ~[Residence4.7.5.0.jar:?]
at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:143) ~[Residence4.7.5.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1592.jar:git-Spigot-4bd94dc-e3b4cf5]
... 15 more`

**Comment by Zrips** [comment]
fc5b241670815997e951e44d2129c79f0d51e1c3
