### ISSUE TITLE
Residence Have problem with WorldEdit Snapshot

### ISSUE THREAD

**Issue by EncryptSL** [Zrips/Residence#176]
Residence Experimental 4.8.0.0 Experimental.
Have Problem with WE version: 7.0.0-SNAPSHOT;3790-e214a02. Snapshot for Version: 1.13.

Spigot Ver: This server is running CraftBukkit version git-Spigot-f68f5a8-0891fc1 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Residence have FoundError with com/sk89q/worldedit/bukkit/selections/Selection

Full Error:
`[12:43:16] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/selections/Selection
	at com.bekvon.bukkit.residence.Residence.setWorldEdit(Residence.java:875) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:715) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.selections.Selection
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-f68f5a8-0891fc1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 13 more`

**Comment by Ghost-chu** [comment]
I had this problem too xD

**Comment by EncryptSL** [comment]
Yep, On old WE Res working. BTW. xD

**Comment by Zrips** [comment]
Fixed
