### ISSUE TITLE
Worldedit issue

### ISSUE THREAD

**Issue by Hawnu** [Zrips/Residence#178]
Hello, Residence not wortk with Worldedit new for 1.13: http://builds.enginehub.org/job/worldedit?branch=string-ids

``[09:06:13] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/selections/Selection
	at com.bekvon.bukkit.residence.Residence.setWorldEdit(Residence.java:875) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:715) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-69774b3-8592585]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.selections.Selection
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-69774b3-8592585]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	... 13 more

**Comment by TheTopCz** [comment]
#173 duplicate

**Comment by Zrips** [comment]
Fixed
