### ISSUE TITLE
Latest version on startup

### ISSUE THREAD

**Issue by Rosain** [Zrips/Residence#179]
`[03:23:39] [Server thread/INFO]: [Residence] Enabling Residence v4.8.0.2
[03:23:40] [Server thread/INFO]: Can't find effect for Selected Frame with this name, it was set to default[m
[03:23:40] [Server thread/INFO]: Can't find effect for Selected Frame with this name, it was set to default[m
[03:23:41] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/Packet
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_181]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:533) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-69774b3-8592585]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-69774b3-8592585]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot.jar:git-Spigot-69774b3-8592585]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-69774b3-8592585]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]`

Plugins:
CoreProtect, LuckPerms, WorldEdit, RemoteToolkitPlugin, mcMMO, BuycraftX, Vault, ProtocolLib, AAC, DiscordSRV, BKCommonLib, React, My_Worlds, RestrictedCreative, ConditionalCommands, CMIEInjector, CMI, Residence
Spigot Version:
git-Spigot-69774b3-8592585 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by Rosain** [comment]
Turns out its not the latest version, my bad.

**Comment by Zrips** [comment]
Should be fixed at this moment
