### ISSUE TITLE
new version worldedit 7.0 cause class not found error

### ISSUE THREAD

**Issue by tianji1993** [Zrips/Residence#238]
Spigot Version: git-Spigot-a1f2566-97b0057 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
WorldEdit: worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar
you can get it from here: https://www.dropbox.com/s/ilvz8yurswp16bb/worldedit-bukkit-7.0.0-SNAPSHOT-dist.zip?dl=0

I'm using worldedit 7.0 on Spigot 1.13.2, when I try to use /resadmin expand this error occurs, seems in WE7.0 they removed api com/sk89q/worldedit/Vector:

Error:
[14:03:46 INFO]: [Yum] Exception: java.lang.NoClassDefFoundError
[14:03:46 INFO]: [Yum] Details: com/sk89q/worldedit/Vector
[14:03:46 INFO]: [Yum]     at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:58)
[14:03:46 INFO]: [Yum]     at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc1(WorldEdit7SelectionManager.java:72)
[14:03:46 INFO]: [Yum]     at com.bekvon.bukkit.residence.commands.expand.perform(expand.java:59)
[14:03:46 INFO]: [Yum]     at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156)

**Comment by Ghost-chu** [comment]
same
[08:54:42 ERROR]: Could not pass event PlayerInteractEvent to Residence v4.8.3.1

java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector

**Comment by Ghost-chu** [comment]
@Zrips

**Comment by arturek1666** [comment]
Same issue :( players get supper mad :(

**Comment by combrich** [comment]
Same issue,I use WorldEdit 7.0.0 Beta 4 (1.13+ ONLY!).residence 4.8.3.1.paperspogit build-474
Full Error:
`[20:36:26 ERROR]: Could not pass event PlayerInteractEvent to Residence v4.8.3.1
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:58) ~[?:?]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:78) ~[?:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onSelection(ResidencePlayerListener.java:1146) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor535.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-474]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:314) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:465) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1359) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-474]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[20:36:27 ERROR]: Could not pass event PlayerInteractEvent to Residence v4.8.3.1
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:58) ~[?:?]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc1(WorldEdit7SelectionManager.java:72) ~[?:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onSelection(ResidencePlayerListener.java:1140) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor535.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-474]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:314) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:281) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1283) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-474]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[20:36:27 ERROR]: Could not pass event PlayerInteractEvent to Residence v4.8.3.1
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:58) ~[?:?]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:78) ~[?:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onSelection(ResidencePlayerListener.java:1146) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor535.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-474]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:314) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:465) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1359) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-474]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
`

**Comment by MothGirlMusic** [comment]
hello. i get this error with world edit: https://pastebin.com/L5CUchLW but with any kind of selection whatsoever. i just bought the plugin to install in my server so i dont have any experience with this at all.

**Comment by MothGirlMusic** [comment]
i'm on spigot though

**Comment by smmmadden** [comment]
The two errors are not the same error and have different servers (PaperSpigot vs Spigot).  The first one should be resolved by using the latest version of WorldEdit 7 from [here](http://builds.enginehub.org/job/worldedit/last-successful?branch=master):.

The second one looks to be permission related (and possibly WorldEdit version/build).  Make sure your user has the necessary [permissions](https://github.com/Zrips/Residence/wiki/Permissions) for that command (residence.select) and other permissions associated with Residence Plugin.  So for you @MothGirlMusic , if you think your permissions are correct, update WE and see if that resolves it.  I can't tell how old git-Spigot-82e117e-01a9959 build is, so if this too is old, I'd suggest rebuilding it.

**Comment by MothGirlMusic** [comment]
git-Spigot-82e117e-01a9959 is the latest dev build as of 2 days ago, and world edit is build #3987 which was released a little over 24 hours ago now. so i can promise they're all updated... but i'll check out the permissions.

and the version/build error might be right.. as i said my server and worldedit are updated, but Residence's last update was back in november. so it very well might be an API mismatch, but if anything, it'd be the plugin's fault being outdated. i'd have to know which worldedit to downgrade to... i'm using FAWE now and it likes it now, but only because it can't see it as world edit.. so none of the regen stuff works. but i can't complain. it works now.. i just hope they update the plugin.

**Comment by smmmadden** [comment]
just for kicks, I tried the same with the /res select 10 5 10 in my residence and it threw the same exception.  I normally don't specify the coordinates that was but use a stick (SelectionToolId: 280) in config.yml for me.  I left click the X spot and then right click the Z spot and have my cube.  You can then use /res select coords and it'll highlight the selected area.  I try to rely on the tools or using //hpos1 and //hpos2 in WorldEdit to mark selections. 

@Zrips - this is a bug using Spigot and Paper Spigot 1.13.2 Build 488 as well.  I'm using the same plugin/versions so it does appear to be an API issue between Residence 4.8.3.1 and WorldEdit 7 builds. 
Thanks -Steve

**Comment by AsaAlv** [comment]
Can also confirm same issue. spigot 1.13.1 / worldedit-bukkit-7.0.0-beta-04

```
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.3.1 
...  
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
```

Happens on different commands /res select /res expand and more

**Comment by Zrips** [comment]
Will be fixed with next update
