### ISSUE TITLE
server crashed after upgrade to latest version of Residence v4.8.4.0

### ISSUE THREAD

**Issue by tianji1993** [Zrips/Residence#246]
error messages:

[02:26:58 INFO]: [Residence] Enabling Residence v4.8.4.0
[02:27:00 INFO]: [Residence] Wrote default config...
[02:27:00 INFO]: [Residence] Wrote default flags...
[02:27:00 INFO]: [Residence] Wrote default groups...
[02:27:00 INFO]: Can't find effect for Selected Frame with this name, it was set to default
[02:27:00 INFO]: Can't find effect for Selected Frame with this name, it was set to default
[02:27:00 INFO]: [Residence] Found Vault using permissions plugin:LuckPerms
[02:27:01 INFO]: [Residence] Disabling Residence v4.8.4.0
[02:27:01 INFO]: [Residence] - FAILED INITIALIZATION! DISABLED! ERROR:
[02:27:01 ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: null
        at com.bekvon.bukkit.residence.commands.flags.getLocale(flags.java:41) ~[?:?]
        at com.bekvon.bukkit.residence.LocaleManager.LoadLang(LocaleManager.java:130) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by Zrips** [comment]
test 4.8.4.1 version
