### ISSUE TITLE
most  commands throw  internal error. plugin unusable

### ISSUE THREAD

**Issue by melinstagibson** [Zrips/Residence#257]
happens since the latest update with nearly all  commands:

```

[15:53:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.4.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1796) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1604) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-507]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-507]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:62) ~[?:?]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:82) ~[?:?]
        at com.bekvon.bukkit.residence.commands.expand.perform(expand.java:60) ~[?:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-507]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-507]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:62) ~[?:?]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:82) ~[?:?]
        at com.bekvon.bukkit.residence.commands.expand.perform(expand.java:60) ~[?:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-507]
        ... 15 more

```

**Comment by melinstagibson** [comment]
same for 4.8.4.3:
```
[16:00:49 INFO]: keriah issued server command: /expand 1
[16:00:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:659) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:37) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-507]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1796) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1604) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-507]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-507]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-507]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:62) ~[?:?]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:82) ~[?:?]
        at com.bekvon.bukkit.residence.commands.expand.perform(expand.java:60) ~[?:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-507]
        ... 19 more
```

**Comment by melinstagibson** [comment]
same for 4.8.4.2 and  4.8.4.1  so  i went back to  4.8.3.1

please fix this quickly

**Comment by arturek1666** [comment]
There is now version: 4.8.4.4 please try this one and if no error please close this issue if fixed.

**Comment by R1NZLER15** [comment]
> There is now version: 4.8.4.4 please try this one and if no error please close this issue if fixed.

Using 4.8.4.4, having the similar issues

**Comment by melinstagibson** [comment]
This error was with 4.8.4.4, thats what i was referring to with "latest update"

**Comment by melinstagibson** [comment]
This is caused when you install FAWE, i know several people here have the same issue.

Use regular worldedit with this version of residence and it will work

**Comment by Zrips** [comment]
258dd504a03d3075c658e28c3caf034104caeabf
This is due to updated WE API which changed quite few things during its development towards 7.x version, so use latest WE and latest Residence and everything should work as it should.
