### ISSUE TITLE
Residence 4.8.4.4 - Can't create residence

### ISSUE THREAD

**Issue by JohnStriker** [Zrips/Residence#267]
Hi there. I have problem with residence.
Spigot 1.13.2
Residence 4.8.4.4

No one can create residence.
https://hasteb.in/eneliroc.sql

`
Save  New  Duplicate & Edit  Just Text
[17:47:33 INFO]: Prophet issued server command: /res select 50 50 50
[17:47:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.4.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:62) ~[?:?]
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:82) ~[?:?]
at com.bekvon.bukkit.residence.selection.SelectionManager.selectBySize(SelectionManager.java:880) ~[?:?]
at com.bekvon.bukkit.residence.commands.select.perform(select.java:195) ~[?:?]
at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:62) ~[?:?]
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:82) ~[?:?]
at com.bekvon.bukkit.residence.selection.SelectionManager.selectBySize(SelectionManager.java:880) ~[?:?]
at com.bekvon.bukkit.residence.commands.select.perform(select.java:195) ~[?:?]
at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
... 15 more

[18:02:21 ERROR]: Could not pass event PlayerInteractEvent to Residence v4.8.4.4
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:457) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1244) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:62) ~[?:?]
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc2(WorldEdit7SelectionManager.java:82) ~[?:?]
at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onSelection(ResidencePlayerListener.java:1155) ~[?:?]
at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
... 17 more`

**Comment by JohnStriker** [comment]
Ok. Now it works but I had to remove FastAsyncWorldEdit :/

**Comment by PajdysOriginal** [comment]
Same issue for me!

**Comment by PajdysOriginal** [comment]
> Same issue for me! Hopefully someone will see it soon! --- WorldGuard -> WorldEdit -> FastAsyncWorldEdit -> Residence doesn't get together!

**Comment by Zrips** [comment]
c88a3c6e7d1851c023d7f1b608bb70cc109298c1
