### ISSUE TITLE
Could not pass event BlockPhysicsEvent to Residence v4.8.4.4

### ISSUE THREAD

**Issue by superb24ED** [Zrips/Residence#268]
Logs:
 ERROR]: Could not pass event BlockPhysicsEvent to Residence v4.8.4.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockPhysicsEvent(CraftEventFactory.java:1244) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.BlockPlant.updateState(BlockPlant.java:18) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.BlockTallPlant.updateState(BlockTallPlant.java:17) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.IBlockData.updateState(SourceFile:297) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DefinedStructure.a(SourceFile:319) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.VoxelShapeDiscrete.a(SourceFile:305) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.VoxelShapeDiscrete.a(SourceFile:282) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DefinedStructure.a(SourceFile:310) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DefinedStructure.a(SourceFile:183) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DefinedStructurePiece.a(SourceFile:59) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.WorldGenFeatureOceanRuinPieces$a.a(SourceFile:269) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.StructureStart.a(SourceFile:62) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.StructureGenerator.generate(StructureGenerator.java:48) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.WorldGenDecoratorEmpty.a(SourceFile:16) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.WorldGenDecoratorEmpty.a(SourceFile:13) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.WorldGenFeatureComposite.a(SourceFile:27) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.BiomeBase.a(SourceFile:504) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.addDecorations(ChunkGeneratorAbstract.java:97) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.addDecorations(NormalChunkGenerator.java:59) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkTaskDecorate.a(SourceFile:12) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:75) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_191]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_191]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) [?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:109) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerChunk.a(SourceFile:87) [spigot-1.13.2.jar:git-Spigot-b0f
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_191]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) [?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:109) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerChunk.a(SourceFile:87) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerChunkMap.flush(PlayerChunkMap.java:135) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:291) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:172) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:114) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:144) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:148) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getChunk(CraftBlock.java:104) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at com.bekvon.bukkit.residence.allNms.v1_13Events.onLandDryPhysics(v1_13Events.java:68) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor335.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        ... 75 more
Caused by: java.lang.RuntimeException: Batch already started.
        at net.minecraft.server.v1_13_R2.SchedulerBatch.b(SourceFile:27) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:108) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:144) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:148) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getChunk(CraftBlock.java:104) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at com.bekvon.bukkit.residence.allNms.v1_13Events.onLandDryPhysics(v1_13Events.java:68) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor335.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        ... 75 more

**Comment by krytoss** [comment]
I have the same problem.

**Comment by kajahofman** [comment]
Me too.

**Comment by SlimeDog** [comment]
And I.

Spigot 1.13.2
Residence 4.8.4.4

This typically happens when a player makes a large jump (ie., teleport) out of a Residence.
