### ISSUE TITLE
Please Help with the residence  I bought from you  version Residence 4.8.4.4

### ISSUE THREAD

**Issue by MCScorpions** [Zrips/Residence#273]
[01:10:34 INFO]: MCScorpions issued server command: /resadmin select  99 99 99 and /res select 99 99 99 please help me thx 
[01:10:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'resadmin' in plugin Residence v4.8.4.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:62) ~[?:?]
at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc1(WorldEdit7SelectionManager.java:76) ~[?:?]
at com.bekvon.bukkit.residence.selection.SelectionManager.selectBySize(SelectionManager.java:879) ~[?:?]
at com.bekvon.bukkit.residence.commands.select.perform(select.java:195) ~[?:?]
at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-e5e5c7c-c24abab]
... 15 more

**Comment by arturek1666** [comment]
Do you have FAWE in any chance?

**Comment by arturek1666** [comment]
Try to use newest version of residence maybe it's fixed now

**Comment by Zrips** [comment]
c88a3c6e7d1851c023d7f1b608bb70cc109298c1
