### ISSUE TITLE
Latest Experimental Build errors

### ISSUE THREAD

**Issue by user127001** [Zrips/Residence#288]
Server can not run with latest build 4.8.6.1 and immediately stopped.
Errors log from Residence:
```
[16:41:38] [Server thread/INFO]: [Residence] Enabling Residence v4.8.6.1
[16:41:39] [Server thread/INFO]: [Residence] Found Vault using permissions plugin:UltraPermissions
[16:41:39] [Server thread/INFO]: [Residence] Scanning for economy systems...
[16:41:39] [Server thread/INFO]: [Residence] Found Vault using economy system: CMIEconomy
[16:41:39] [Server thread/INFO]: [Residence] Loading save data for world w...
[16:41:39] [Server thread/INFO]: [Residence] Loaded w data. (6 ms)
[16:41:39] [Server thread/INFO]: [Residence] Loading save data for world w_nether...
[16:41:39] [Server thread/INFO]: [Residence] Loaded w_nether data. (0 ms)
[16:41:39] [Server thread/INFO]: [Residence] Loading save data for world w_the_end...
[16:41:39] [Server thread/INFO]: [Residence] Loaded w_the_end data. (0 ms)
[16:41:39] [Server thread/INFO]: [Residence] Loading w data into memory...
[16:41:39] [Server thread/INFO]: [Residence] Loaded w data into memory. (0 ms)
[16:41:39] [Server thread/INFO]: [Residence] Loading w_nether data into memory...
[16:41:39] [Server thread/INFO]: [Residence] Loaded w_nether data into memory. (0 ms)
[16:41:39] [Server thread/INFO]: [Residence] Loading w_the_end data into memory...
[16:41:39] [Server thread/INFO]: [Residence] Loaded w_the_end data into memory. (0 ms)
[16:41:39] [Server thread/INFO]: [Residence] Disabling Residence v4.8.6.1
[16:41:39] [Server thread/INFO]: [Residence] - FAILED INITIALIZATION! DISABLED! ERROR:
[16:41:39] [Server thread/ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: null
	at java.util.EnumMap.typeCheck(Unknown Source) ~[?:1.8.0_211]
	at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_211]
	at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_211]
	at com.bekvon.bukkit.residence.protection.FlagPermissions.addMaterialToUseFlag(FlagPermissions.java:65) ~[?:?]
	at com.bekvon.bukkit.residence.protection.FlagPermissions.initValidFlags(FlagPermissions.java:234) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:750) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[16:41:39] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.6.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:515) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:220) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:216) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:167) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:136) ~[patched_1.13.2.jar:git-Paper-624]
	at com.bekvon.bukkit.cmiLib.VersionChecker.VersionCheck(VersionChecker.java:154) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:873) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

Paper 1.13.2

Best regards

**Comment by Zrips** [comment]
40b763a8a2512d21f01d47bf793c1a79e87e40ff
