### ISSUE TITLE
Unable to remove claims from previous version

### ISSUE THREAD

**Issue by GlitchKing79** [Zrips/Residence#290]
Unable to remove claims that were created on Residence4.8.5, while using Residence4.8.6.2Experimental

>org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.6.2 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.bekvon.bukkit.residence.protection.ClaimedResidence.isOwner(ClaimedResidence.java:1809) ~[?:?]
at com.bekvon.bukkit.residence.commands.remove.perform(remove.java:57) ~[?:?]
at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
... 17 more`

**Comment by Zrips** [comment]
ab4fd0321f9db3fc5ddd18aad67ed77b9ec89ccf
This in general should help out, tho it would be interesting to see save file entry for both residences, created after and before release.
