### ISSUE TITLE
EZPlaceholderHook deprecated

### ISSUE THREAD

**Issue by SlimeDog** [Zrips/Residence#293]
Spigot 1.13.2 final and 1.14 (2268)
PlaceholderAPI 2.10.0-b65
Residence 4.8.6.2

Per [PlaceholderAPI](http://ci.extendedclip.com/job/PlaceholderAPI/changes):
```
#65 (May 5, 2019 10:40:16 AM)
Remove EZPlaceholderHook which has been deprecated for over a year. (commit: 6495a38) — Ryan McCarthy / githubweb
``` 
Consequently, placeholders do not work.

On server start-up
```
[08:03:55] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.6.2 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/external/EZPlaceholderHook
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:132) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:200) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:93) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.setupPlaceHolderAPI(Residence.java:879) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:803) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.external.EZPlaceholderHook
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 22 more
```

**Comment by SlimeDog** [comment]
PlaceholderAPI dev [put it back temporarily](https://github.com/PlaceholderAPI-Expansions/PlaceholderAPI/commit/75c3027e055867f9b1f1f529b743db679f5668e6), but you really need to update.

**Comment by user127001** [comment]
Already fixed in CMI. I am sure the Residence will next.

**Comment by SlimeDog** [comment]
How can you be sure? Only the dev can be sure.

**Comment by SlimeDog** [comment]
And the clock is ticking...
[QUOTE="ItsMeGlare, post: 3394796, member: 477275"]This is just a friendly reminder than in less than 24 hours, any plugins using EzPlaceholderHook will no longer register their placeholders. Make sure if you're using it that you update to the newer methods![/QUOTE]

**Comment by user127001** [comment]
Well, I'm starting to worry too.
PAPI already on Phase Two of removing EzPlaceholderHook from the plugin.

**Comment by SlimeDog** [comment]
I didn't say I was worried. :)

If you deploy the latest PlaceholderAPI, I expect that Residence placeholders will fail. That's not an issue on my servers; I was trying to nudge Zrips anyway, since I use the plugin.

**Comment by WHiZSTA** [comment]
i did update, and yeah they fail to work. from the console:

11.05 05:40:59 [Server] Server thread/ERROR [PlaceholderAPI] Residence is currently using a deprecated method to hook into PlaceholderAPI. Placeholders for that plugin no longer work. Please consult [bekvon, nate302, t00thpick1] and urge them to update it ASAP.

**Comment by Zrips** [comment]
124e080792105b742f4373429bc8575e4941cd27
