### ISSUE TITLE
can't use /res set

### ISSUE THREAD

**Issue by p82183645** [Zrips/Residence#302]
`[17:10:08 INFO]: AriaMura issued server command: /res set
[17:10:08 WARN]: [Residence] Plugin Residence v4.8.6.3 generated an exception while executing task 13698328
java.lang.NullPointerException: null
        at com.bekvon.bukkit.residence.gui.SetFlag.recalculateResidence(SetFlag.java:245) ~[?:?]
        at com.bekvon.bukkit.residence.commands.set$1.run(set.java:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-626]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-626]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-626]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

can't use /res set
Residence  4.8.6.3
paper 1.13.2

**Comment by Straiker123** [comment]
try default config.

**Comment by p82183645** [comment]
> try default config.

Residence4.8.5.0.jar can use

**Comment by Zrips** [comment]
dc730251f19f3a2fdf5e34947080b0b031f515a0
