### ISSUE TITLE
/res set ---  GUI erro [1.13.2]

### ISSUE THREAD

**Issue by mctool** [Zrips/Residence#304]
`[17:02:46 INFO]: Ral_rxd issued server command: /res set
[17:02:46 WARN]: [Residence] Plugin Residence v4.8.6.3 generated an exception while executing task 574916
java.lang.NullPointerException: null
        at com.bekvon.bukkit.residence.gui.SetFlag.recalculateResidence(SetFlag.java:245) ~[?:?]
        at com.bekvon.bukkit.residence.commands.set$1.run(set.java:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-626]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-626]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-626]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_202]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]`

**Comment by mercurialmusic** [comment]
Getting the same. I thought it was related to the UUID thing, but now I'm not sure. Also getting it when people are in the /res set GUI and they click next, it doesn't turn the page. Clicking it twice skips the second page and shows the third page. It's kinda weird.

**Comment by Zrips** [comment]
dc730251f19f3a2fdf5e34947080b0b031f515a0
