### ISSUE TITLE
plugin wont load

### ISSUE THREAD

**Issue by melinstagibson** [Zrips/Residence#316]
everytime i restart the server i get this and it shuts down again.
i have to remove residence, load it with plugman and then restart the server again and it works...
```
[12:59:04 ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: null
        at com.bekvon.bukkit.residence.economy.CMIEconomy.add(CMIEconomy.java:36) ~[?:?]
        at com.bekvon.bukkit.residence.economy.TransactionManager.giveEconomyMoney(TransactionManager.java:79) ~[?:?]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:592) ~[?:?]
        at com.bekvon.bukkit.residence.utils.FileCleanUp.cleanFiles(FileCleanUp.java:73) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:743) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-630]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[12:59:04 ERROR]: Error occurred while enabling Residence v4.8.6.4 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:515) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:220) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:216) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:167) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:136) ~[patched_1.13.2.jar:git-Paper-630]
        at com.bekvon.bukkit.cmiLib.VersionChecker.VersionCheck(VersionChecker.java:152) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:872) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-630]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-630]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-630]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]```

**Comment by Speedy11CZ** [comment]
I have this error too.

**Comment by Zrips** [comment]
a25ae1567492fd5c1f45de9d1ca9feb9af7cc901
