### ISSUE TITLE
/res set error  paper-1.14.2

### ISSUE THREAD

**Issue by mcpanglei** [Zrips/Residence#317]
[12:24:50 INFO]: mcpanglei issued server command: /res set
[12:24:50 WARN]: [Residence] Plugin Residence v4.8.6.3 generated an exception while executing task 3190
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[patched_1.14.2.jar:git-Paper-86]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:117) ~[?:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:59) ~[?:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:54) ~[?:?]
        at com.bekvon.bukkit.residence.commands.set$1.run(set.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.2.jar:git-Paper-86]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.2.jar:git-Paper-86]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

**Comment by mcpanglei** [comment]
Residence v4.8.6.4 also！

**Comment by Zrips** [comment]
f8354ef96e40861f08472bc487626f25e0f4fa22
