### ISSUE TITLE
Linger Potion Splash Event Issue

### ISSUE THREAD

**Issue by CharlyZhu** [Zrips/Residence#336]
I am using the latest version of 1.13.2, when my player uses a lingering potion, it will spam NoSuchMethod error in console, saying that LingerSplashPotion.getEntity() is no longer a method. Could you please do something about this.

The error log is pasted below:
[09:57:27] [Server thread/ERROR]: Could not pass event LingeringPotionSplashEvent to Residence v4.8.6.6
java.lang.NoSuchMethodError: org.bukkit.event.entity.LingeringPotionSplashEvent.getEntity()Lorg/bukkit/entity/ThrownPotion;
	at com.bekvon.bukkit.residence.allNms.v1_9Events.onLingeringSplashPotion(v1_9Events.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor278.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-639]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callLingeringPotionSplashEvent(CraftEventFactory.java:552) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:213) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:88) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.EntityProjectile.tick(EntityProjectile.java:160) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1561) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1528) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1339) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-639]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[09:57:41] [Server thread/ERROR]: Could not pass event LingeringPotionSplashEvent to Residence v4.8.6.6
java.lang.NoSuchMethodError: org.bukkit.event.entity.LingeringPotionSplashEvent.getEntity()Lorg/bukkit/entity/ThrownPotion;
	at com.bekvon.bukkit.residence.allNms.v1_9Events.onLingeringSplashPotion(v1_9Events.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor278.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-639]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callLingeringPotionSplashEvent(CraftEventFactory.java:552) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:213) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.EntityPotion.a(EntityPotion.java:88) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.EntityProjectile.tick(EntityProjectile.java:160) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1561) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1528) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1339) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-639]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[09:57:56] [Server thread/INFO]: xinky lost connection: Disconnected

**Comment by Zrips** [comment]
912b4399a56a1f378f01e20b6ed40deaaeb89ce2
