### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by DejVIIKBob** [Zrips/Residence#343]
[Server thread/ERROR]: null
java.lang.NullPointerException: null
     at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:562) ~[Residence4.8.7.0DevBuild.jar:?]
     at com.bekvon.bukkit.residence.utils.FileCleanUp.cleanFiles(FileCleanUp.java:74) ~[Residence4.8.7.0DevBuild.jar:?]
     at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:743) [Residence4.8.7.0DevBuild.jar:?]
     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[19:11:47] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.7.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:447) ~[minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:200) ~[minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:196) ~[minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:147) ~[minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:116) ~[minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at com.bekvon.bukkit.cmiLib.VersionChecker.VersionCheck(VersionChecker.java:152) ~[?:?]
     at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:872) ~[?:?]
     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [minecraft_server.jar:git-Spigot-e5b1b5d-803eaa3]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by Zrips** [comment]
Disable residence regeneration on cleanup for time being, will push out new version soon enough which should have fix for this.
6a15744b211abf4f9a7e22bce73b9049bf95a965
