### ISSUE TITLE
Help buy the plugin but it did not work I get this error, How can I solve that?

### ISSUE THREAD

**Issue by Abizy** [Zrips/Residence#344]
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to Residence v4.8.7.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[custom.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[custom.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [custom.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:173) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:154) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:220) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1092) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [custom.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [custom.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoClassDefFoundError: com/Zrips/CMI/Modules/Permissions/PermissionInfo
        at com.bekvon.bukkit.residence.permissions.PermissionManager.addToCache(PermissionManager.java:512) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:386) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:361) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:357) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:325) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager.isResidenceAdmin(PermissionManager.java:103) ~[?:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerJoin(ResidencePlayerListener.java:915) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[custom.jar:git-Spigot-9de398a-9c887d4]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.Modules.Permissions.PermissionInfo
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[custom.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[custom.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at com.bekvon.bukkit.residence.permissions.PermissionManager.addToCache(PermissionManager.java:512) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:386) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:361) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:357) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:325) ~[?:?]
        at com.bekvon.bukkit.residence.permissions.PermissionManager.isResidenceAdmin(PermissionManager.java:103) ~[?:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerJoin(ResidencePlayerListener.java:915) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[custom.jar:git-Spigot-9de398a-9c887d4]
        ... 13 more

**Comment by Zrips** [comment]
got fixed
