### ISSUE TITLE
/res dont working on 1.14

### ISSUE THREAD

**Issue by Hucoo** [Zrips/Residence#356]
Here is an error from console, when i tiping /res command.

` issued server command: /res 
>[2K [08:29:55] [Server thread/ERROR]: null 
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.7.1 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [server.jar:git-Spigot-9de398a-9c887d4] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] 
Caused by: java.lang.NoClassDefFoundError: com/Zrips/CMI/Modules/Permissions/PermissionInfo 
at com.bekvon.bukkit.residence.permissions.PermissionManager.addToCache(PermissionManager.java:512) ~[?:?] 
at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:386) ~[?:?] 
at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:361) ~[?:?] 
at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:357) ~[?:?] 
at com.bekvon.bukkit.residence.permissions.PermissionManager$ResPerm.hasPermission(PermissionManager.java:325) ~[?:?] 
at com.bekvon.bukkit.residence.permissions.PermissionManager.isResidenceAdmin(PermissionManager.java:103) ~[?:?] 
at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:55) ~[?:?] 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-9de398a-9c887d4] 
... 17 more `

**Comment by Brom3X** [comment]
Yeah, I have the same issue aswell!

**Comment by Hucoo** [comment]
> Yeah, I have the same issue aswell!

Download updated version :) its working
