### ISSUE TITLE
Crash log on start server [1.7.10]

### ISSUE THREAD

**Issue by Tyz3** [Zrips/Residence#363]
[Residence] Enabling Residence v4.8.7.2
java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Item
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.bekvon.bukkit.cmiLib.ItemReflection.getMinecraftClass(ItemReflection.java:67)
	at com.bekvon.bukkit.cmiLib.ItemReflection.initialize(ItemReflection.java:51)
	at com.bekvon.bukkit.cmiLib.ItemReflection.<clinit>(ItemReflection.java:27)
	at com.bekvon.bukkit.cmiLib.ItemManager.load(ItemManager.java:77)
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:448)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/ItemStack
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.bekvon.bukkit.cmiLib.ItemReflection.getMinecraftClass(ItemReflection.java:67)
	at com.bekvon.bukkit.cmiLib.ItemReflection.initialize(ItemReflection.java:56)
	at com.bekvon.bukkit.cmiLib.ItemReflection.<clinit>(ItemReflection.java:27)
	at com.bekvon.bukkit.cmiLib.ItemManager.load(ItemManager.java:77)
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:448)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Zrips** [comment]
34ddd20a0a1583f3d91f75dab539d8871d73b5c9
Will be in working order with next update
