### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Nety01** [Zrips/Residence#369]
Hi, I can sometimes see this error in console:
https://pastebin.com/ZQ1uDr5n

Server version: Paper 1.13.2
Plugin version: 4.8.7.3

**Comment by In77** [comment]
Res 4.8.7.3 running on Paper 1.14.4 (git-Paper-186) also have this problem

[17:11:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Residence v4.8.7.3
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.placingMinecart(ResidencePlayerListener.java:1217) ~[?:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerInteract(ResidencePlayerListener.java:1242) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor447.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:421) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:136) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[PaperClip-1.14.4-b186.jar:git-Paper-186]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

**Comment by 100petr** [comment]
Same issue. Server: 1.12.2 residence: 4.8.7.3.

**Comment by Zrips** [comment]
1753be71c687d11a71968bec53da0fac86c0bf06
