### ISSUE TITLE
Java excepctions listing all residences from console

### ISSUE THREAD

**Issue by WyRe** [Zrips/Residence#41]
I'm having got that exceptions when I try list all residences existing in the server:

```
[13:40:29] [Server thread/INFO]: -----< Page 1 of 3 (45) >-----
[13:40:29] [Server thread/INFO]:  1. Alquiler1 - world (For rent) Owner: _WyRe_ (X:150 Y:70 Z:317; X:136 Y:58 Z:291) Created on: Thu 2017.03.30 at 08:14:19 PM CEST Cost: 1000 per 5 days Can Renew: true Rentable stay in market: true Rentable allows auto pay: true
[13:40:29] [Server thread/INFO]:  2. azulo - world  Owner: violapescatore (X:91 Y:77 Z:220; X:77 Y:56 Z:205) Created on: Sun 2017.05.07 at 08:34:57 PM CEST
[13:40:29] [Server thread/INFO]:  3. camino - world  Owner: DrYoel (X:115 Y:71 Z:314; X:51 Y:65 Z:312) Created on: Mon 2017.05.01 at 03:37:53 AM CEST
[13:40:29] [Server thread/INFO]:  4. CasaAdriSer - world  Owner: ElAdrigamer (X:250 Y:105 Z:536; X:156 Y:49 Z:429) Created on: Fri 2017.04.28 at 04:05:49 PM CEST
[13:40:29] [Server thread/INFO]:  5. CasaEdu - world  Owner: Eduardo (X:119 Y:76 Z:282; X:109 Y:63 Z:254) Created on: Tue 2017.04.04 at 09:12:45 PM CEST
[13:40:29] [Server thread/INFO]:  6. CasaEdu1 - world  Owner: Eduardo (X:124 Y:76 Z:282; X:120 Y:62 Z:271) Created on: Tue 2017.04.04 at 09:19:24 PM CEST
[13:40:29] [Server thread/INFO]:  7. casalago2 - world  Owner: DrYoel (X:21 Y:73 Z:149; X:-12 Y:62 Z:121) Created on: Mon 2017.05.01 at 06:20:08 AM CEST
[13:40:29] [Server thread/INFO]:  8. casalago3 - world  Owner: ariXgamertroll (X:57 Y:73 Z:162; X:24 Y:62 Z:134) Created on: Mon 2017.05.01 at 06:20:37 AM CEST
[13:40:29] [Server thread/INFO]:  9. casalago5 - world  Owner: DrYoel (X:61 Y:72 Z:234; X:32 Y:61 Z:201) Created on: Mon 2017.05.01 at 06:23:03 AM CEST
[13:40:29] [Server thread/INFO]:  10. casalago7 - world  Owner: AngelTeRectea_YT (X:-5 Y:73 Z:261; X:-38 Y:61 Z:231) Created on: Mon 2017.05.01 at 06:23:57 AM CEST
[13:40:29] [Server thread/INFO]:  11. casalago8 - world  Owner: redvXD_YT (X:-50 Y:73 Z:228; X:-80 Y:61 Z:195) Created on: Mon 2017.05.01 at 06:26:59 AM CEST
[13:40:29] [Server thread/INFO]:  12. casalago9 - world  Owner: Raphel2111 (X:-50 Y:73 Z:193; X:-80 Y:61 Z:160) Created on: Mon 2017.05.01 at 06:28:19 AM CEST
[13:40:29] [Server thread/INFO]:  13. casalagoplus - world  Owner: DrYoel (X:61 Y:73 Z:199; X:26 Y:61 Z:166) Created on: Mon 2017.05.01 at 04:16:25 AM CEST
[13:40:29] [Server thread/INFO]:  14. casalagorogersito - world  Owner: Rogersitoo (X:-20 Y:75 Z:159; X:-52 Y:61 Z:128) Created on: Wed 2017.05.03 at 06:36:59 PM CEST
[13:40:29] [Server thread/INFO]:  15. CasaPixel - world  Owner: Pixel (X:331 Y:80 Z:-119; X:318 Y:57 Z:-148) Created on: Thu 2017.04.06 at 05:13:08 AM CEST
[13:40:29] [Server thread/INFO]:  16. casaredvXD_YT - world  Owner: redvXD_YT (X:58 Y:63 Z:266; X:53 Y:56 Z:253) Created on: Sat 2017.04.29 at 05:24:56 PM CEST
[13:40:29] [Server thread/INFO]:  17. CasaWyRe - world  Owner: _WyRe_ (X:410 Y:130 Z:768; X:364 Y:51 Z:725) Created on: Sun 2017.01.22 at 06:31:28 PM CET
[13:40:29] [Server thread/INFO]:  18. DespachoWyRe - world  Owner: _WyRe_ (X:269 Y:83 Z:224; X:254 Y:78 Z:209) Created on: Thu 2017.04.06 at 08:28:44 PM CEST
[13:40:29] [Server thread/INFO]:  19. DrYoel - world  Owner: DrYoel (X:-3 Y:96 Z:199; X:-19 Y:58 Z:183) Created on: Mon 2017.05.01 at 06:03:39 AM CEST
[13:40:29] [Server thread/INFO]:  20. ElTrioCalavera - world  Owner: TheKkelvinGreens (X:-468 Y:67 Z:794; X:-496 Y:63 Z:751) Created on: Mon 2017.04.03 at 09:37:49 PM CEST
[13:40:29] [Server thread/WARN]: Unexpected exception while parsing console command "res listall 1"
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.6.1.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.bekvon.bukkit.residence.text.help.InformationPager.printListWithDelay(InformationPager.java:175) ~[?:?]
	at com.bekvon.bukkit.residence.text.help.InformationPager.printListInfo(InformationPager.java:81) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.listAllResidences(ResidenceManager.java:318) ~[?:?]
	at com.bekvon.bukkit.residence.commands.listall.perform(listall.java:47) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:143) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	... 8 more
[13:40:42] [Server thread/INFO]: -----< Page 2 of 3 (45) >-----
[13:40:42] [Server thread/INFO]:  21. Alquiler1 - world (For rent) Owner: _WyRe_ (X:150 Y:70 Z:317; X:136 Y:58 Z:291) Created on: Thu 2017.03.30 at 08:14:19 PM CEST Cost: 1000 per 5 days Can Renew: true Rentable stay in market: true Rentable allows auto pay: true
[13:40:42] [Server thread/INFO]:  22. azulo - world  Owner: violapescatore (X:91 Y:77 Z:220; X:77 Y:56 Z:205) Created on: Sun 2017.05.07 at 08:34:57 PM CEST
[13:40:42] [Server thread/INFO]:  23. camino - world  Owner: DrYoel (X:115 Y:71 Z:314; X:51 Y:65 Z:312) Created on: Mon 2017.05.01 at 03:37:53 AM CEST
[13:40:42] [Server thread/INFO]:  24. CasaAdriSer - world  Owner: ElAdrigamer (X:250 Y:105 Z:536; X:156 Y:49 Z:429) Created on: Fri 2017.04.28 at 04:05:49 PM CEST
[13:40:42] [Server thread/INFO]:  25. CasaEdu - world  Owner: Eduardo (X:119 Y:76 Z:282; X:109 Y:63 Z:254) Created on: Tue 2017.04.04 at 09:12:45 PM CEST
[13:40:42] [Server thread/INFO]:  26. CasaEdu1 - world  Owner: Eduardo (X:124 Y:76 Z:282; X:120 Y:62 Z:271) Created on: Tue 2017.04.04 at 09:19:24 PM CEST
[13:40:42] [Server thread/INFO]:  27. casalago2 - world  Owner: DrYoel (X:21 Y:73 Z:149; X:-12 Y:62 Z:121) Created on: Mon 2017.05.01 at 06:20:08 AM CEST
[13:40:42] [Server thread/INFO]:  28. casalago3 - world  Owner: ariXgamertroll (X:57 Y:73 Z:162; X:24 Y:62 Z:134) Created on: Mon 2017.05.01 at 06:20:37 AM CEST
[13:40:42] [Server thread/INFO]:  29. casalago5 - world  Owner: DrYoel (X:61 Y:72 Z:234; X:32 Y:61 Z:201) Created on: Mon 2017.05.01 at 06:23:03 AM CEST
[13:40:42] [Server thread/INFO]:  30. casalago7 - world  Owner: AngelTeRectea_YT (X:-5 Y:73 Z:261; X:-38 Y:61 Z:231) Created on: Mon 2017.05.01 at 06:23:57 AM CEST
[13:40:42] [Server thread/INFO]:  31. casalago8 - world  Owner: redvXD_YT (X:-50 Y:73 Z:228; X:-80 Y:61 Z:195) Created on: Mon 2017.05.01 at 06:26:59 AM CEST
[13:40:42] [Server thread/INFO]:  32. casalago9 - world  Owner: Raphel2111 (X:-50 Y:73 Z:193; X:-80 Y:61 Z:160) Created on: Mon 2017.05.01 at 06:28:19 AM CEST
[13:40:42] [Server thread/INFO]:  33. casalagoplus - world  Owner: DrYoel (X:61 Y:73 Z:199; X:26 Y:61 Z:166) Created on: Mon 2017.05.01 at 04:16:25 AM CEST
[13:40:42] [Server thread/INFO]:  34. casalagorogersito - world  Owner: Rogersitoo (X:-20 Y:75 Z:159; X:-52 Y:61 Z:128) Created on: Wed 2017.05.03 at 06:36:59 PM CEST
[13:40:42] [Server thread/INFO]:  35. CasaPixel - world  Owner: Pixel (X:331 Y:80 Z:-119; X:318 Y:57 Z:-148) Created on: Thu 2017.04.06 at 05:13:08 AM CEST
[13:40:42] [Server thread/INFO]:  36. casaredvXD_YT - world  Owner: redvXD_YT (X:58 Y:63 Z:266; X:53 Y:56 Z:253) Created on: Sat 2017.04.29 at 05:24:56 PM CEST
[13:40:42] [Server thread/INFO]:  37. CasaWyRe - world  Owner: _WyRe_ (X:410 Y:130 Z:768; X:364 Y:51 Z:725) Created on: Sun 2017.01.22 at 06:31:28 PM CET
[13:40:42] [Server thread/INFO]:  38. DespachoWyRe - world  Owner: _WyRe_ (X:269 Y:83 Z:224; X:254 Y:78 Z:209) Created on: Thu 2017.04.06 at 08:28:44 PM CEST
[13:40:42] [Server thread/INFO]:  39. DrYoel - world  Owner: DrYoel (X:-3 Y:96 Z:199; X:-19 Y:58 Z:183) Created on: Mon 2017.05.01 at 06:03:39 AM CEST
[13:40:42] [Server thread/INFO]:  40. ElTrioCalavera - world  Owner: TheKkelvinGreens (X:-468 Y:67 Z:794; X:-496 Y:63 Z:751) Created on: Mon 2017.04.03 at 09:37:49 PM CEST
[13:40:42] [Server thread/WARN]: Unexpected exception while parsing console command "res listall 2"
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.6.1.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.bekvon.bukkit.residence.text.help.InformationPager.printListWithDelay(InformationPager.java:175) ~[?:?]
	at com.bekvon.bukkit.residence.text.help.InformationPager.printListInfo(InformationPager.java:81) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.listAllResidences(ResidenceManager.java:318) ~[?:?]
	at com.bekvon.bukkit.residence.commands.listall.perform(listall.java:47) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:143) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	... 8 more
[13:40:44] [Server thread/INFO]: -----< Page 3 of 3 (45) >-----
[13:40:44] [Server thread/INFO]:  41. Alquiler1 - world (For rent) Owner: _WyRe_ (X:150 Y:70 Z:317; X:136 Y:58 Z:291) Created on: Thu 2017.03.30 at 08:14:19 PM CEST Cost: 1000 per 5 days Can Renew: true Rentable stay in market: true Rentable allows auto pay: true
[13:40:44] [Server thread/INFO]:  42. azulo - world  Owner: violapescatore (X:91 Y:77 Z:220; X:77 Y:56 Z:205) Created on: Sun 2017.05.07 at 08:34:57 PM CEST
[13:40:44] [Server thread/INFO]:  43. camino - world  Owner: DrYoel (X:115 Y:71 Z:314; X:51 Y:65 Z:312) Created on: Mon 2017.05.01 at 03:37:53 AM CEST
[13:40:44] [Server thread/INFO]:  44. CasaAdriSer - world  Owner: ElAdrigamer (X:250 Y:105 Z:536; X:156 Y:49 Z:429) Created on: Fri 2017.04.28 at 04:05:49 PM CEST
[13:40:44] [Server thread/INFO]:  45. CasaEdu - world  Owner: Eduardo (X:119 Y:76 Z:282; X:109 Y:63 Z:254) Created on: Tue 2017.04.04 at 09:12:45 PM CEST

```

**Comment by Zrips** [comment]
Should be fixed with next build
