### ISSUE TITLE
Setting an Invalid Owner Corrupts the Residence

### ISSUE THREAD

**Issue by architecture4less** [Zrips/Residence#412]
Hi, I'm using spigot-1.15.1 and Residence 4.8.8.2.

I issued the command `/resadmin setowner spawn server`, and it broke my 'spawn' residence. Entering or leaving the residence caused further errors. Residence also printed an error that it was unable to save my residence. I tried using the commands `/resadmin set flowinprotection true` and `/resadmin info` afterwards with additional errors. Luckily, when the server restarted, the broken residence was gone.

Here are the stack traces:
```
[16:42:38] [Server thread/INFO]: Cynadyde issued server command: /resadmin setowner spawn server
[16:42:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'resadmin' in plugin Residence v4.8.8.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.getOwner(ResidencePermissions.java:582) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.applyDefaultFlags(ResidencePermissions.java:485) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.setOwner(ResidencePermissions.java:576) ~[?:?]
	at com.bekvon.bukkit.residence.commands.setowner.perform(setowner.java:31) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:170) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	... 17 more
[16:44:34] [Server thread/ERROR]: Could not pass event ResidenceChangedEvent to Residence v4.8.8.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.handleNewLocation(ResidencePlayerListener.java:2109) ~[?:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerMove(ResidencePlayerListener.java:1997) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:998) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.isOwner(ClaimedResidence.java:1851) ~[?:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onResidenceChangeMessagePrint(ResidencePlayerListener.java:2330) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor320.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	... 26 more
[16:46:46] [Craft Scheduler Thread - 79/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m[0;31;1m Failed to save residence (spawn)![m
[16:46:46] [Craft Scheduler Thread - 79/ERROR]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.save(ResidencePermissions.java:606) ~[Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.save(ClaimedResidence.java:1511) ~[Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.save(ResidenceManager.java:851) [Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.Residence.saveYml(Residence.java:1234) [Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.Residence.access$0(Residence.java:1229) [Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.Residence$6$1.run(Residence.java:377) [Residence4.8.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[16:48:16] [Server thread/INFO]: Cynadyde issued server command: /resadmin set flowinprotection true
[16:48:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'resadmin' in plugin Residence v4.8.8.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.isOwner(ClaimedResidence.java:1851) ~[?:?]
	at com.bekvon.bukkit.residence.commands.set.perform(set.java:34) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:170) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	... 17 more
[16:48:27] [Server thread/INFO]: Cynadyde issued server command: /resadmin info
[16:48:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'resadmin' in plugin Residence v4.8.8.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:893) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.getOwner(ResidencePermissions.java:582) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.printAreaInfo(ResidenceManager.java:695) ~[?:?]
	at com.bekvon.bukkit.residence.commands.info.perform(info.java:26) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:170) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.12.2.jar:git-Spigot-492a779-fde78ef]
	... 17 more
```

**Comment by Zrips** [comment]
efd5bd94971707e6f3ba91601e6edac52b8bc872
