### ISSUE TITLE
Failed initialization! Disabled!

### ISSUE THREAD

**Issue by SubBass100** [Zrips/Residence#414]
I've just purchased Residence (Thank you it sounds really cool). I am running a 1.15.1 Spigot Server with EssentialsX economy and upon booting I receive this error. Any help would be greatly appriciated. Thank you!

`[22:31:15] [Server thread/INFO]: [Residence] Enabling Residence v4.8.8.2
[22:31:17] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found LuckPerms4 Plugin![m
[22:31:17] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Scanning for economy systems...[m
[22:31:17] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Vault NOT found![m
[22:31:17] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m CMIEconomy NOT found![m
[22:31:17] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m BOSEconomy NOT found![m
[22:31:17] [Server thread/INFO]: [Residence] Disabling Residence v4.8.8.2
[22:31:18] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m - FAILED INITIALIZATION! DISABLED! ERROR:[m
[22:31:18] [Server thread/ERROR]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.getServerLandName(Residence.java:1779) ~[Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.economy.EssentialsEcoAdapter.<init>(EssentialsEcoAdapter.java:17) ~[Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.Residence.loadEssentialsEconomy(Residence.java:1164) ~[Residence4.8.8.2.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:653) [Residence4.8.8.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:31:18] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.8.2 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:447) ~[spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:200) ~[spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:196) ~[spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:147) ~[spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:116) ~[spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at com.bekvon.bukkit.cmiLib.VersionChecker.VersionCheck(VersionChecker.java:152) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:871) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.1.jar:git-Spigot-05bb8bc-8510673]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Nety01** [comment]
Download Vault plugin

**Comment by Zrips** [comment]
ee4db8e6529e0f073fc52351f6d2c3cdfedb7448
