### ISSUE TITLE
plugin not working at 1.15.2 version

### ISSUE THREAD

**Issue by alan67160** [Zrips/Residence#415]
**ERROR :**
```
22.01 15:45:28 [Server] WARN Unexpected exception while parsing console command "res"
22.01 15:45:28 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'res' in plugin Residence v4.8.8.2 - plugin is disabled.
22.01 15:45:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:702) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:462) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:424) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-64]
22.01 15:45:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
---

**Residence Version:** 8.6.15.5

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper version git-Paper-64 (MC: 1.15.2)

**Comment by Zrips** [comment]
I need first error message you got related to residence plugin. It should be at startup

**Comment by alan67160** [comment]
It fixed on Paper version git-Paper-65 (MC: 1.15.2)

**Comment by alan67160** [comment]
`[10:58:25] [Server thread/INFO]: [Residence] Enabling Residence v4.8.8.2
[10:58:27] [Server thread/INFO]: [Residence] Found Vault using permissions plugin:LuckPerms
[10:58:27] [Server thread/INFO]: [Residence] Scanning for economy systems...
[10:58:27] [Server thread/INFO]: [Residence] Found Vault using economy system: CMIEconomy
[10:58:27] [Server thread/INFO]: [Residence] Loading save data for world world...
[10:58:27] [Server thread/INFO]: [Residence] Loaded world data. (2 ms)
[10:58:27] [Server thread/INFO]: [Residence] Loading save data for world world_nether...
[10:58:27] [Server thread/INFO]: [Residence] Loaded world_nether data. (1 ms)
[10:58:27] [Server thread/INFO]: [Residence] Loading save data for world world_the_end...
[10:58:27] [Server thread/INFO]: [Residence] Loaded world_the_end data. (0 ms)
[10:58:27] [Server thread/INFO]: [Residence] Loading world data into memory...
[10:58:27] [Server thread/INFO]: [Residence] Loaded world data into memory. (24 ms) -> 5 residences
[10:58:27] [Server thread/INFO]: [Residence] Loading world_nether data into memory...
[10:58:27] [Server thread/INFO]: [Residence] Loaded world_nether data into memory. (0 ms) -> 0 residences
[10:58:27] [Server thread/INFO]: [Residence] Loading world_the_end data into memory...
[10:58:27] [Server thread/INFO]: [Residence] Loaded world_the_end data into memory. (3 ms) -> 2 residences
[10:58:27] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/WorldEditPlugin
[10:58:27] [Server thread/WARN]: 	at com.bekvon.bukkit.residence.Residence.setWorldEdit(Residence.java:908)
[10:58:27] [Server thread/WARN]: 	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:750)
[10:58:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:58:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[10:58:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[10:58:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[10:58:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[10:58:27] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[10:58:27] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:291)
[10:58:27] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[10:58:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:58:27] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.WorldEditPlugin
[10:58:27] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[10:58:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150)
[10:58:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[10:58:27] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:58:27] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:58:27] [Server thread/WARN]: 	... 11 more
[10:58:27] [Server thread/ERROR]: Error occurred while enabling Residence v4.8.8.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WorldGuardPlugin
	at com.bekvon.bukkit.residence.Residence.setWorldGuard(Residence.java:955) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:751) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-64]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.2.jar:git-Paper-64]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.2.jar:git-Paper-64]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.2.jar:git-Paper-64]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.2.jar:git-Paper-64]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-64]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:291) ~[patched_1.15.2.jar:git-Paper-64]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-64]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WorldGuardPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150) ~[patched_1.15.2.jar:git-Paper-64]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.15.2.jar:git-Paper-64]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	... 11 more
[10:58:27] [Server thread/INFO]: [Residence] Disabling Residence v4.8.8.2`

**Comment by Zrips** [comment]
update worldedit and worldguard, they are causing issues. Tho will make some changes to prevent this from happening in the future.
