### ISSUE TITLE
cannot load on Glowstone

### ISSUE THREAD

**Issue by tsao-chi** [Zrips/Residence#416]
log:
```
00:56:16 [INFO] Enabling Residence v4.8.8.2
00:56:16 [SEVERE] Error occurred while enabling Residence v4.8.8.2 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
	at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:427)
	at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:269)
	at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1061)
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:495)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:819)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.cmiLib.VersionChecker$Version.isCurrentEqualOrLower(VersionChecker.java:144)
	at com.bekvon.bukkit.cmiLib.CMIMaterial.updateMaterial(CMIMaterial.java:1161)
	at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:39)
	... 12 more
00:56:16 [INFO] Disabling Residence v4.8.8.2
00:56:16 [SEVERE] Error occurred while disabling Residence v4.8.8.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.bekvon.bukkit.cmiLib.ItemManager
	at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
	at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:427)
	at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:269)
	at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1061)
	at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:405)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:354)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:819)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
```

**Comment by Zrips** [comment]
Glowstone is not supported because they are using completely different internal API and having support for it would require quite allot of additional code.
