### ISSUE TITLE
/res set

### ISSUE THREAD

**Issue by Niko302** [Zrips/Residence#435]
/res set doesn't work on the latest 
4.9.0.2
>.... [19:20:32 WARN]: [Residence] Plugin Residence v4.9.0.2 generated an exception while executing task 619341
java.lang.NullPointerException: null

**Comment by Niko302** [comment]
Did /res reload flags and removed
https://media.discordapp.net/attachments/526403195476639744/690288709504991454/newconfigs.PNG?width=1442&height=85
and it works again

**Comment by mercurialmusic** [comment]
Confirming. Only error I get in console is:
```
> [21:20:06] [Server thread/INFO]: mercurialmusic issued server command: /res set
> [21:20:06] [Craft Scheduler Thread - 711/WARN]: [Residence] Plugin Residence v4.9.0.2 generated an exception while executing task 2209978
java.lang.NullPointerException: null
```

/res reload flags did not work for me, but I can try regenerating the file.

I'm using Residence 4.9.0.2 on CraftBukkit version git-Spigot-6de3d4b-a6f8093 (MC: 1.15.2)

Seems like `/res list [name]` and `/res list all` are also broken - only shows my own residences.

**Comment by mercurialmusic** [comment]
After regenerating the flags.yml nothing changes in game, but I get slightly more error in console:
```
> [21:41:00] [Server thread/INFO]: mercurialmusic issued server command: /res set
> [21:41:00] [Craft Scheduler Thread - 10/WARN]: [Residence] Plugin Residence v4.9.0.2 generated an exception while executing task 5344
java.lang.NullPointerException: null
at com.bekvon.bukkit.residence.protection.FlagPermissions.has(FlagPermissions.java:558) ~[?:?]
at com.bekvon.bukkit.residence.protection.ResidencePermissions.has(ResidencePermissions.java:145) ~[?:?]
at com.bekvon.bukkit.residence.protection.ResidencePermissions.has(ResidencePermissions.java:135) ~[?:?]
at com.bekvon.bukkit.residence.gui.setFlagInfo.updateLook(setFlagInfo.java:300) ~[?:?]
at com.bekvon.bukkit.residence.gui.setFlagInfo.recalculateResidence(setFlagInfo.java:147) ~[?:?]
at com.bekvon.bukkit.residence.gui.setFlagInfo.recalculate(setFlagInfo.java:90) ~[?:?]
at com.bekvon.bukkit.residence.gui.FlagUtil$4.run(FlagUtil.java:134) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-6de3d4b-a6f8093]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-6de3d4b-a6f8093]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by Zrips** [comment]
feaec75dd4569736229c5e9b4b61dae5ab316e06

**Comment by mercurialmusic** [comment]
Note quite: https://gist.github.com/mercurialmusic/87bedee62fef0531c70996d78ab1ca11

**Comment by mercurialmusic** [comment]
All good! Thanks!
