### ISSUE TITLE
Permission checks and RaidListener lag spikes

### ISSUE THREAD

**Issue by Luky584** [Zrips/Residence#437]
Hello,
I am dealing with lag spikes over last few versions.

Here are my timings: https://timings.aikar.co/?id=bb4900d0806d421cb53c63076b8cd968
And profiler report: https://sparkprofiler.github.io/#b5FyuI2kl5

There seems to be a problem with raid listener Residence::Event: c.b.b.r.r.ResidenceRaidListener (ResidenceFlagCheckEvent)
and with com.bekvon.bukkit.residence.containers.ResidencePlayer.RecalculatePermissions()

There seems to be **global problem with permission checking and recalculating** according to profiler results.

It feels like 4.9.0.3 is worse than the 4.8.8.2.
I have Raid disabled, so I think these checks are not necessary. 

I hope those results will help.

**Comment by Luky584** [comment]
Also, from 4.9.x there is null poiner error
```
[12:58:07 INFO]: vv8cz issued server command: /res set
[12:58:07 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.9.0.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1615]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1615]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1615]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1615]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1615]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: `java.lang.NullPointerException
```

**Comment by Zrips** [comment]
This actually helps out quite a bit. Will make adjustments to eliminate the majority if not all of this load on server.

**Comment by Luky584** [comment]
Thanks!

**Comment by Zrips** [comment]
And could you provide a second part of that error? As now most important part is missing, which indicates where this error originated exactly.

**Comment by Luky584** [comment]
I am so sorry, but this is the only thing i get..
https://i.imgur.com/xhf98jV.png

**Comment by Zrips** [comment]
Yea, this usually is caused by some console filer cutting down part of error log.

**Comment by Luky584** [comment]
All problems solved, thank you!

4.9.0.4 is awesome!
