### ISSUE TITLE
cant use res auto

### ISSUE THREAD

**Issue by blank826** [Zrips/Residence#446]
[16:26:22 INFO]: blank826 issued server command: /res auto sdf
[16:26:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.8.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.8.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:357) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at com.bekvon.bukkit.residence.commands.auto.perform(auto.java:133) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:170) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	... 15 more
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.CuboidRegion.getPos1()Lcom/sk89q/worldedit/math/BlockVector3;
	at com.bekvon.bukkit.residence.selection.WorldEditSelectionManager.worldEdit(WorldEditSelectionManager.java:34) ~[?:?]
	at com.bekvon.bukkit.residence.commands.create.perform(create.java:30) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:170) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:357) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	at com.bekvon.bukkit.residence.commands.auto.perform(auto.java:133) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:170) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
	... 15 more

**Comment by Zrips** [comment]
8b6101fb38edd74e20ba09ac247fa692f478f917
