### ISSUE TITLE
java.lang.NullPointerException with GroupManager

### ISSUE THREAD

**Issue by KristopherKram** [Zrips/Residence#457]
I've recently installed Residence but I'm getting a java.lang.NullPointerException error on startup.
Server: Spigot
Residence v4.9.0.5
`[01:46:20] [Server thread/INFO]: [Residence] Enabling Residence v4.9.0.5

[01:46:20] [Server thread/INFO]: [Residence] Found Vault using permissions plugin:GroupManager
[01:46:20] [Server thread/ERROR]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.protection.WorldFlagManager.parsePerms(WorldFlagManager.java:75) [Residence-4.9.0.5.jar:?]
	at com.bekvon.bukkit.residence.protection.WorldFlagManager.<init>(WorldFlagManager.java:31) [Residence-4.9.0.5.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:540) [Residence-4.9.0.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:46:20] [Server thread/INFO]: [Residence] Scanning for economy systems...
[01:46:20] [Server thread/INFO]: [Residence] Found Vault using economy system: Essentials Economy
[01:46:20] [Server thread/INFO]: [Residence] Loading (6) player data
[01:46:20] [Server thread/INFO]: [Residence] Player data loaded: 6
[01:46:21] [Server thread/WARN]: [Residence] Save directory does not exist...
[01:46:21] [Server thread/WARN]: [Residence] Please restart server
[01:46:21] [Server thread/INFO]: [Residence] Found WorldEdit 7.1.0;8e55131
[01:46:21] [Server thread/INFO]: [Residence] Found WorldGuard 7.0.2-SNAPSHOT;bf2593e
[01:46:21] [Server thread/INFO]: [Residence] DynMap residence activated!
[01:46:21] [Server thread/INFO]: [Residence] Enabled! Version 4.9.0.5 by Zrips`
Please let me know if you need any more information.

**Comment by PintaPepo** [comment]
Could you test if #467 fixes your problem?

**Comment by Zrips** [comment]
33c276dc2f61c2d244f7c4ed8c944f8d287bff73
