### ISSUE TITLE
Spigot 1.12 pre release exception

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#48]
Seems this may be a Dynmap issue (which I reported on that plugin page), but wanted to make sure it is known here to confirm once Dynmap is fixed, this gets resolved by it?
[08:56:31] [Server thread/INFO]: [Residence] Enabling Residence v4.6.3.1
[08:56:31] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found Vault using permissions plugin:PermissionsEx[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Scanning for economy systems...[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found Vault using economy system: SaneEconomy[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loading save data for world world...[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded world data. (5 ms)[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loading save data for world world_nether...[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded world_nether data. (1 ms)[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loading save data for world world_the_end...[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded world_the_end data. (1 ms)[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loading world data into memory...[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded world data into memory. (21 ms)[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loading world_nether data into memory...[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded world_nether data into memory. (0 ms)[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loading world_the_end data into memory...[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded world_the_end data into memory. (0 ms)[m
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found WorldEdit[m
[08:56:32] [Server thread/INFO]: [Residence] Disabling Residence v4.6.3.1
[08:56:32] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m - FAILED INITIALIZATION! DISABLED! ERROR:[m
[08:56:32] [Server thread/ERROR]: null
java.lang.NullPointerException: null
	at org.dynmap.bukkit.DynmapPlugin.getMarkerAPI(DynmapPlugin.java:943) ~[dynmap-2.4.jar:?]
	at com.bekvon.bukkit.residence.dynmap.DynMapManager.activate(DynMapManager.java:293) ~[Residence4.6.3.1.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:693) [Residence4.6.3.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[08:56:32] [Server thread/ERROR]: Error occurred while enabling Residence v4.6.3.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:118) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:101) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at com.bekvon.bukkit.residence.utils.VersionChecker.VersionCheck(VersionChecker.java:110) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:749) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by Zrips** [comment]
Yea its issue from dynmap, will do some changes to bypass this one and just inform about outdated API in future.

**Comment by smmmadden** [comment]
Thanks!
