### ISSUE TITLE
1.7.10 Modpack warning

### ISSUE THREAD

**Issue by Syndrixxx** [Zrips/Residence#481]
Hi, when I run this plugin on modpack server 1.7.10, I get these warnings on startup, and then, when I write some commands like "/res delete Residence", I get Internal server error or sth like that

[01:52:07 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/ChatSerializer
[01:52:07 WARN]: at java.lang.Class.forName0(Native Method)
[01:52:07 WARN]: at java.lang.Class.forName(Class.java:264)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.getMinecraftClass(CMIReflections.java:261)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.initialize(CMIReflections.java:45)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.<clinit>(CMIReflections.java:35)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:53)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:551)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:293)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1071)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:490)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[01:52:07 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[01:52:07 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[01:52:07 WARN]: at java.lang.Thread.run(Thread.java:748)
[01:52:07 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutOpenWindow
[01:52:07 WARN]: at java.lang.Class.forName0(Native Method)
[01:52:07 WARN]: at java.lang.Class.forName(Class.java:264)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.getMinecraftClass(CMIReflections.java:261)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.initialize(CMIReflections.java:66)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.<clinit>(CMIReflections.java:35)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:53)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:551)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:293)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1071)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:490)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[01:52:07 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[01:52:07 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[01:52:07 WARN]: at java.lang.Thread.run(Thread.java:748)
[01:52:07 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/NBTTagCompound
[01:52:07 WARN]: at java.lang.Class.forName0(Native Method)
[01:52:07 WARN]: at java.lang.Class.forName(Class.java:264)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.getMinecraftClass(CMIReflections.java:261)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.initialize(CMIReflections.java:71)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.<clinit>(CMIReflections.java:35)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:53)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:551)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:293)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1071)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:490)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[01:52:07 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[01:52:07 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[01:52:07 WARN]: at java.lang.Thread.run(Thread.java:748)
[01:52:07 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Item
[01:52:07 WARN]: at java.lang.Class.forName0(Native Method)
[01:52:07 WARN]: at java.lang.Class.forName(Class.java:264)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.getMinecraftClass(CMIReflections.java:261)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.initialize(CMIReflections.java:91)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.<clinit>(CMIReflections.java:35)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:53)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:551)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:293)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1071)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:490)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[01:52:07 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[01:52:07 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[01:52:07 WARN]: at java.lang.Thread.run(Thread.java:748)
[01:52:07 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/ItemStack
[01:52:07 WARN]: at java.lang.Class.forName0(Native Method)
[01:52:07 WARN]: at java.lang.Class.forName(Class.java:264)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.getMinecraftClass(CMIReflections.java:261)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.initialize(CMIReflections.java:96)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIReflections.<clinit>(CMIReflections.java:35)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:53)
[01:52:07 WARN]: at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:551)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:293)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1071)
[01:52:07 WARN]: at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:490)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[01:52:07 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[01:52:07 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[01:52:07 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[01:52:07 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[01:52:07 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[01:52:07 WARN]: at java.lang.Thread.run(Thread.java:748)

Could I get some help please? I don't know how to fix it

**Comment by Zrips** [comment]
it fails on recognizing some of the classes by server version. No idea what type of moded server you have and what server version its reporting, but its failing on multiple fronts and will not work properly. If there is free version i can test i might find solution, if not, then you will need to check some what more up to date moded minecraft server and avoid using 6 year old one.
