### ISSUE TITLE
[1.16.1] Fatal error, unable to load on start

### ISSUE THREAD

**Issue by mrfloris** [Zrips/Residence#489]
```
[04:19:05] [Server thread/INFO]: Time elapsed: 975 ms
[04:19:05] [Server thread/INFO]: [Residence] Enabling Residence v4.9.0.6
[04:19:05] [Server thread/INFO]: [Residence] Wrote default flags...
[04:19:05] [Server thread/INFO]: [Residence] Wrote default groups...
[04:19:07] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[04:19:10] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16 and server will shutdown
[04:19:10] [Server thread/INFO]: [Residence] - FAILED INITIALIZATION! DISABLED! ERROR:
[04:19:10] [Server thread/ERROR]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:397) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:531) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[04:19:10] [Server thread/ERROR]: Error occurred while enabling Residence v4.9.0.6 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:453) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:205) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:201) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:152) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:121) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at com.bekvon.bukkit.cmiLib.VersionChecker.VersionCheck(VersionChecker.java:152) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:822) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[04:19:10] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[04:19:10] [Server thread/INFO]: Done (21.592s)! For help, type "help"
[04:19:10] [Server thread/INFO]: Stopping server
[04:19:10] [Server thread/INFO]: [Vault] Disabling Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[04:19:10] [Server thread/INFO]: Saving players
[04:19:10] [Server thread/INFO]: Saving worlds
[04:19:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[04:19:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[04:19:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[04:19:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04:19:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[04:19:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04:19:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[04:19:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04:19:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
>%                                                                                                                     
 floris@Floriss-iMac z-residence %
```
This one even crashes the server.
```
>ver
[04:11:48] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[04:11:48] [Server thread/INFO]: Checking version, please wait...
[04:11:48] [Thread-7/INFO]: You are running the latest version
>
```

**Comment by Baterka** [comment]
It needs update... Which is not easy when many old dependencies (old plugin supports) are already dead and we do not have them.

**Comment by Zrips** [comment]
7e15b1b9fc8349c55b61e237f8225447800c2613
