### ISSUE TITLE
Unable to tab complete

### ISSUE THREAD

**Issue by TONY-All** [Zrips/Residence#495]
Log is here 
```
[07:00:55] [Server thread/ERROR]: Exception when TONY_Uname attempted to tab complete res create
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/res create' in plugin Residence v4.9.1.0
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.tabCompleteCommand(CraftServer.java:1736) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.tabComplete(CraftServer.java:1708) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at org.bukkit.craftbukkit.v1_16_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:536) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.PacketPlayInTabComplete.a(SourceFile:35) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:944) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:937) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:921) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:853) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:165) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.residence.text.help.HelpEntry.getSubCommands(HelpEntry.java:289) ~[?:?]
	at com.bekvon.bukkit.residence.utils.TabComplete.onTabComplete(TabComplete.java:21) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[spigot.jar:git-Spigot-758abbe-b5db08b]
	... 23 more
```

**Comment by Zrips** [comment]
0b98b8251269a8e05c5ff623b0bddcafab5d4546
