### ISSUE TITLE
Exception in /res info command

### ISSUE THREAD

**Issue by matbcvo** [Zrips/Residence#500]
When entering `/res info` command then exception appears in server console.

Residence 4.9.1.1
Paper 1.16.1 build 34

```
[01:18:29] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[01:18:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:18:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:18:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:18:29] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[01:18:29] [Server thread/WARN]: 	at com.bekvon.bukkit.cmiLib.RawMessageManager.send(RawMessageManager.java:64)
[01:18:29] [Server thread/WARN]: 	at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:631)
[01:18:29] [Server thread/WARN]: 	at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:615)
[01:18:29] [Server thread/WARN]: 	at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:661)
[01:18:29] [Server thread/WARN]: 	at com.bekvon.bukkit.residence.protection.ResidenceManager.printAreaInfo(ResidenceManager.java:746)
[01:18:29] [Server thread/WARN]: 	at com.bekvon.bukkit.residence.commands.info.perform(info.java:46)
[01:18:29] [Server thread/WARN]: 	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:267)
[01:18:29] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:18:29] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[01:18:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[01:18:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:18:29] [Server thread/WARN]: Caused by: com.google.gson.JsonParseException: Unexpected empty array of components
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:229)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:148)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101)
[01:18:29] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:517)
[01:18:29] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:358)
[01:18:29] [Server thread/WARN]: 	... 30 more
[01:18:29] [Server thread/INFO]: Failed to show json message with packets, using command approach
[01:18:29] [Server thread/INFO]: Invalid chat component: Unexpected empty array of components
[01:18:29] [Server thread/INFO]: ..."Typhome" ["",{"text":"","extra":[{"text":"Players flags: "}]},{"text":"","extra":[{"text":"Winter526"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"container move shear use destroy \nadmin animalkilling beacon mobkilling build \nchat tp leash "}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"Zer0Int0Madness"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"container ignite move shear use \ndestroy animalkilling trade mobkilling build \nvehicledestroy leash "}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"Typhome"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"container move shear use destroy \nanimalkilling beacon mobkilling build chat \ntp leash "}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"AquaAura1"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"container move shear use admin \ndestroy animalkilling beacon mobkilling build \nchat tp leash "}]}}},{"text":"","extra":[ ]}]<--[HERE]
```

**Comment by Zrips** [comment]
Fixed with latest builds
