### ISSUE TITLE
/res info spam

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#505]
Hi, when someone uses /res info on the newest version: 4.9.1.1 on Paper **1.15.2**, there is this spam:
```
[22:30:59 INFO]: Failed to show json message with packets, using command approach
[22:30:59 INFO]: Invalid chat component: Unexpected empty array of components
[22:30:59 INFO]: ... "Bxrd3r" ["",{"text":"","extra":[{"text":"Vlajky hráčů: "}]},{"text":"","extra":[{"text":"minec123_"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"build"}]}}},{"text":"","extra":[ ]}]<--[HERE]
[22:31:02 WARN]: java.lang.reflect.InvocationTargetException
[22:31:02 WARN]: at jdk.internal.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
[22:31:02 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:31:02 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[22:31:02 WARN]: at com.bekvon.bukkit.cmiLib.RawMessageManager.send(RawMessageManager.java:64)
[22:31:02 WARN]: at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:631)
[22:31:02 WARN]: at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:615)
[22:31:02 WARN]: at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:661)
[22:31:02 WARN]: at com.bekvon.bukkit.residence.protection.ResidenceManager.printAreaInfo(ResidenceManager.java:746)
[22:31:02 WARN]: at com.bekvon.bukkit.residence.commands.info.perform(info.java:46)
[22:31:02 WARN]: at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:267)
[22:31:02 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:31:02 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:31:02 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1866)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1674)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974)
[22:31:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:832)
[22:31:02 WARN]: Caused by: com.google.gson.JsonParseException: Unexpected empty array of components
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:315)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:231)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:184)
[22:31:02 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[22:31:02 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:445)
[22:31:02 WARN]: ... 28 more
[22:31:02 INFO]: Failed to show json message with packets, using command approach
```

Probably due to 1.16.1 version or?

**Comment by Zrips** [comment]
Got fixed with latest version
