### ISSUE TITLE
Error when tab complete

### ISSUE THREAD

**Issue by Mengbill** [Zrips/Residence#522]
Version1.16-R0.1 -SNAPSHOT
Exception when Mengbill attempted to tab complete res reload config
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/res reload config' in plugin Residence v4.9.1.3
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[Server.jar:git-Paper-40]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[Server.jar:git-Paper-40]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[Server.jar:git-Paper-40]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.tabCompleteCommand(CraftServer.java:1873) ~[Server.jar:git-Paper-40]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.tabComplete(CraftServer.java:1845) ~[Server.jar:git-Paper-40]
        at org.bukkit.craftbukkit.v1_16_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[Server.jar:git-Paper-40]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[Server.jar:git-Paper-40]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[Server.jar:git-Paper-40]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.PlayerConnection.lambda$a$4(PlayerConnection.java:587) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[Server.jar:git-Paper-40]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Server.jar:git-Paper-40]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
        at com.bekvon.bukkit.residence.text.help.HelpEntry.getSubCommands(HelpEntry.java:298) ~[?:?]
        at com.bekvon.bukkit.residence.utils.TabComplete.onTabComplete(TabComplete.java:21) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[Server.jar:git-Paper-40]
        ... 20 more

**Comment by Zrips** [comment]
d50057a0f66e0a96d85effd44050854446729e48
