### ISSUE TITLE
Issue with CS-core Lib

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#529]
Hi, sometimes when server starts there's issue with CS-CoreLib. I asked on their support and it's still issue of Residence implementation.
```
[08:13:27] [Server thread/ERROR]: [CS-CoreLib2] [CS-CoreLib2 - Protection] An Error occured while querying the Protection Module: "Residence v4.9.1.6"
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.isResAdminOn(Residence.java:1221) ~[?:?]
	at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.cancelBlockBreak(ResidenceBlockListener.java:200) ~[?:?]
	at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:45) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:191) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.MinerAndroid.dig(MinerAndroid.java:42) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.Instruction.lambda$static$6(Instruction.java:60) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.Instruction.execute(Instruction.java:167) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.ProgrammableAndroid.executeInstruction(ProgrammableAndroid.java:668) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.ProgrammableAndroid.tick(ProgrammableAndroid.java:639) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.androids.ProgrammableAndroid$3.tick(ProgrammableAndroid.java:205) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:131) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tick$1(TickerTask.java:111) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-128]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-128]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-128]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-128]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-128]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-128]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-128]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by dixiatielu** [comment]
I've met the same issue ;)

**Comment by Zrips** [comment]
d061c9d09c6e07b1dfe8b5ebf539bafa9f0aa61b
