### ISSUE TITLE
RandomTeleport

### ISSUE THREAD

**Issue by gotv12** [Zrips/Residence#546]
Hello! I use this plugin for random teleport - https://polymart.org/resource/randomteleport.136 and when I get the residence and put it in the server it stops working.. How to fix that?

RT ERROR -

[01:21:45 WARN]: [RandomTeleport] [RandomTeleport] Plugin RandomTeleport v7.13.2 generated an exception while executing task 5860
java.lang.NoClassDefFoundError: org/kingdoms/manager/game/GameManagement
at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_262]
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_262]
at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_262]
at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_262]
at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_262]
at com.vk2gpz.randomteleport.a.c.k.t.b(t.java:34) ~[?:?]
at com.vk2gpz.randomteleport.a.c.k.t.f(t.java:109) ~[?:?]
at com.vk2gpz.randomteleport.a.c.k.a.d(a.java:295) ~[?:?]
at com.vk2gpz.randomteleport.a.c.k.a.e(a.java:282) ~[?:?]
at com.vk2gpz.randomteleport.b.b(b.java:745) ~[?:?]
at com.vk2gpz.randomteleport.b.d(b.java:529) ~[?:?]
at com.vk2gpz.randomteleport.b$e.run(b$e.java:418) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-135]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-135]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.ClassNotFoundException: org.kingdoms.manager.game.GameManagement
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-135]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-135]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
... 18 more

Everytime I try to use /rtp
When I remove the Residence pluging , it starts to work again..

**Comment by 100petr** [comment]
Do you use Essentials? You can use /tpr from it. And set the alias to rtp in commands.yml
