### ISSUE TITLE
The newest v4.9.1.9 conflicts with Slimefun v4.1.15

### ISSUE THREAD

**Issue by howlandhhy** [Zrips/Residence#563]
I have installed pre plugins correctly, and I am using paperspigot 1.12.2
specific logs are followed

> *******************************
*Residence version v4.9.1.9  *
*Slimefun   version v4.1.15   *
*******************************
[18:36:49 INFO]: [Slimefun] Enabling Slimefun v4.1.15
[18:36:49 ERROR]: Error occurred while enabling Slimefun v4.1.15 (Is it up to date?)
java.lang.NullPointerException: null
        at com.bekvon.bukkit.residence.protection.FlagPermissions.addFlag(FlagPermissions.java:100) ~[?:?]
        at me.mrCookieSlime.Slimefun.SlimefunStartup.onEnable(SlimefunStartup.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[18:36:49 INFO]: [Slimefun] Disabling Slimefun v4.1.15
[18:36:49 ERROR]: Error occurred while disabling Slimefun v4.1.15 (Is it up to date?)
java.lang.NullPointerException: null
        at me.mrCookieSlime.Slimefun.SlimefunStartup.onDisable(SlimefunStartup.java:411) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[18:36:49 INFO]: [Residence] Enabling Residence v4.9.1.9
[18:36:49 INFO]: [Residence] Wrote default flags...
[18:36:49 INFO]: [Residence] Wrote default groups...
[18:36:50 INFO]: [Residence] Found Vault using permissions plugin:GroupManager
[18:36:50 ERROR]: Error occurred while enabling Residence v4.9.1.9 (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/cscorelib2/protection/ProtectionModule
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:569) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionModule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 12 more
[18:36:50 INFO]: [Residence] Disabling Residence v4.9.1.9

**Comment by Zrips** [comment]
c9a6104c9e5593c0cac8f117a0e32d68b9fb311d
