### ISSUE TITLE
Conflicts with many plug-ins

### ISSUE THREAD

**Issue by 1425115471** [Zrips/Residence#576]
Paper-1.16.3-b214.jar
Residence 4.9.1.9.jar

[2020-10-06-22.log](https://github.com/Zrips/Residence/files/5347644/2020-10-06-22.log)

**Comment by 1425115471** [comment]
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.protection.FlagPermissions.addFlag(FlagPermissions.java:100) ~[?:?]
	at net.Indyuce.mmoitems.comp.flags.ResidenceFlags.<init>(ResidenceFlags.java:14) ~[?:?]
	at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:237) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[Paper-1.16.3-b214.jar:git-Paper-214]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.3-b214.jar:git-Paper-214]

**Comment by Zrips** [comment]
Not a residence issue. MMOItems trying to add flag before Residence plugin got initialized which caused this error. To resolve this MMOItems need to add residence as softdepend.
