### ISSUE TITLE
Doesn't support Minecraft 1.16.4

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [Zrips/Residence#591]
[18:17:51] [Server thread/INFO]: [Residence] Enabling Residence v4.9.1.9
[18:17:51] [Server thread/ERROR]: Error occurred while enabling Residence v4.9.1.9 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1443) ~[?:?]
	at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:559) ~[?:?]
	at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:296) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1077) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:489) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-259]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.cmiLib.Version.isCurrentEqualOrLower(Version.java:100) ~[?:?]
	at com.bekvon.bukkit.cmiLib.CMIMaterial.updateMaterial(CMIMaterial.java:1285) ~[?:?]
	at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:34) ~[?:?]
	... 15 more
[18:17:51] [Server thread/INFO]: [Residence] Disabling Residence v4.9.1.9
[18:17:51] [Server thread/ERROR]: Error occurred while disabling Residence v4.9.1.9 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:402) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-259]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by EkonC** [comment]
Please update Residence to 4.9.2.0
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-16.11480/
