### ISSUE TITLE
mmoitems error

### ISSUE THREAD

**Issue by RedCarl** [Zrips/Residence#611]
[10:37:44] [Server thread/INFO]: [MMOLib] Loading MMOLib v1.7
[10:37:44] [Server thread/INFO]: [MMOLib] Detected Bukkit Version: v1_16_R3
[10:37:44] [Server thread/INFO]: [MMOItems] Loading MMOItems v6.5
[10:37:45] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing MMOItems v6.5 (Is it up to date?)
java.lang.NullPointerException: null
	at net.Indyuce.mmoitems.comp.mmocore.MMOCoreMMOLoader.<init>(MMOCoreMMOLoader.java:51) ~[?:?]
	at net.Indyuce.mmoitems.MMOItems.onLoad(MMOItems.java:147) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.4.jar:git-Paper-267]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-267]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-267]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

[10:37:59] [Server thread/INFO]: [MMOItems] Loading template modifiers, please wait..
[10:37:59] [Server thread/INFO]: [MMOItems] Loading item templates, please wait..
[10:37:59] [Server thread/INFO]: [MMOItems] Hooked onto Vault
[10:37:59] [Server thread/INFO]: [MMOItems] Loading crafting stations, please wait..
[10:37:59] [Server thread/ERROR]: Error occurred while enabling MMOItems v6.5 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.protection.FlagPermissions.addFlag(FlagPermissions.java:100) ~[?:?]
	at net.Indyuce.mmoitems.comp.flags.ResidenceFlags.<init>(ResidenceFlags.java:14) ~[?:?]
	at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:230) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-267]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-267]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-267]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-267]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-267]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-267]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-267]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-267]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[10:37:59] [Server thread/INFO]: [MMOItems] Disabling MMOItems v6.5

![image](https://user-images.githubusercontent.com/71010647/101303660-7d573e80-3879-11eb-84f6-8bd7136aacf3.png)

**Comment by Zrips** [comment]
Maybe there isint issue with their code but they do try to add flags before Residence plugin is loaded which caused this issue. Will make some adjustments to prevent plugins doing this in future to avoid issue. Tho they still need to add Residence to softdepend or update their code to properly add flags after residence plugin is loaded. 
af93604a436012e84041f9d4beaf3ceb877ea08f
