### ISSUE TITLE
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.9.2.3

### ISSUE THREAD

**Issue by nicklly** [Zrips/Residence#639]
Server: Tuinity 1.12.2
Plugins: 4.9.2.3
Slimefun version: 4.1.15

I am using the smilefun plug-in and the Residence plug-in at the same time. When the Residence contains a large number of slimfun machines, the following error code appears when entering /res set 

`[21:07:20] [Server thread/INFO]: XxJiuShangxX issued server command: /res set
[21:07:20] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.9.2.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[kSpigot.jar:git-Paper-33d42c8e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[kSpigot.jar:git-Paper-33d42c8e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[kSpigot.jar:git-Paper-33d42c8e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:862) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[kSpigot.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[kSpigot.jar:git-Paper-33d42c8e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.residence.gui.setFlagInfo.updateLook(setFlagInfo.java:323) ~[?:?]
	at com.bekvon.bukkit.residence.gui.setFlagInfo.recalculateResidence(setFlagInfo.java:147) ~[?:?]
	at com.bekvon.bukkit.residence.gui.setFlagInfo.recalculate(setFlagInfo.java:90) ~[?:?]
	at com.bekvon.bukkit.residence.gui.FlagUtil.openSetFlagGui(FlagUtil.java:119) ~[?:?]
	at com.bekvon.bukkit.residence.commands.set.perform(set.java:67) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:272) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[kSpigot.jar:git-Paper-33d42c8e]
	... 15 more`

**Comment by Zrips** [comment]
a18be567f7fc6480a835e5dcbc29c7cf0b6c4c60
