### ISSUE TITLE
/res remove bug

### ISSUE THREAD

**Issue by bigsmileling** [Zrips/Residence#65]
Hi.

I found another bug, its the same bug like i reported some days ago with the /res give

When you do /res remove the residence is not deleted in the list, and its taking an slot

https://image.prntscr.com/image/YdNtBT9OS2ewmH82cIWxeA.png

And still existing in the map, removed https://image.prntscr.com/image/p_q1N5DLTFKUj7-YHZZWmg.png

The only way for fix it is doing /resreload but i dont want do it every 10 minutes, because lagg the server

**Comment by melinstagibson** [comment]
same here, happened after swtiching for 4.6.x to 4.7.x

Just that it never works if i do /res remove. it has nothing to do with /res give, the unclaiming mechanics arent working properly

**Comment by melinstagibson** [comment]
@Zrips please this is major

**Comment by Zrips** [comment]
Working on it. Will post new version soon.

**Comment by melinstagibson** [comment]
Still persists
```
[18:46:43 ERROR]: Could not pass event ResidenceDeleteEvent to Residence v4.7.0.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1133]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1133]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1133]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.jar:git-Paper-1133]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:483) [residence.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:442) [residence.jar:?]
        at com.bekvon.bukkit.residence.utils.FileCleanUp.cleanFiles(FileCleanUp.java:70) [residence.jar:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:631) [residence.jar:?]
        at com.bekvon.bukkit.residence.Residence.reloadPlugin(Residence.java:326) [residence.jar:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:52) [residence.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:669) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:461) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1133]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
```
