### ISSUE TITLE
Got error in console while using 'res pset [residence name]  [player] [flag] [true/false]' command

### ISSUE THREAD

**Issue by XiaoMingXD** [Zrips/Residence#662]
Every time I use the 'res pset [residence name]  [player] [flag] [true/false]' command, no matter I use that in game or the console, I got same error in console and command won't do anything.
I'm using Residence v4.9.2.6 on Thermos 1.7.10.1614-58.

e.g. res pset 777 Human trusted true

[14:18:42 WARN]: Unexpected exception while parsing console command "res pset 777 Human trusted true"
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.9.2.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:720) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:474) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoClassDefFoundError: com/bekvon/bukkit/residence/protection/ClaimedResidence
        at com.bekvon.bukkit.residence.raid.ResidenceRaid.isRaidInitialized(ResidenceRaid.java:386) ~[?:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.setPlayerFlag(ResidencePermissions.java:350) ~[?:?]
        at com.bekvon.bukkit.residence.commands.pset.perform(pset.java:77) ~[?:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:272) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
        ... 8 more

**Comment by Zrips** [comment]
Redownload plugin and perform full server restart. This is usually caused by corrupted jar file or incorrect plugin loading.
