### ISSUE TITLE
Exception?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#682]
```
[12:10:51 WARN]: [Residence] Plugin Residence v4.9.2.10 generated an exception while executing task 3993088
java.lang.NullPointerException: null
        at com.bekvon.bukkit.residence.protection.CuboidArea.<init>(CuboidArea.java:51) ~[?:?]
        at com.bekvon.bukkit.residence.selection.SelectionManager.MakeBorders(SelectionManager.java:684) ~[?:?]
        at com.bekvon.bukkit.residence.selection.SelectionManager$1.run(SelectionManager.java:518) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_281]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_281]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
```

**Comment by Zrips** [comment]
df59cc2f39b148dcbba95cd4a266b54302ac75ba
