### ISSUE TITLE
#65 (/res remove bug) Persists in 4702

### ISSUE THREAD

**Issue by melinstagibson** [Zrips/Residence#69]
Pls fix :/ everytime this happens a user gets the title message displayed on each step he makes in a corruptedly deleted claim :/ plus he cant claim because its somehow not deleted
```
[18:46:43 ERROR]: Could not pass event ResidenceDeleteEvent to Residence v4.7.0.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1133]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1133]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1133]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.jar:git-Paper-1133]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:483) [residence.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:442) [residence.jar:?]
        at com.bekvon.bukkit.residence.utils.FileCleanUp.cleanFiles(FileCleanUp.java:70) [residence.jar:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:631) [residence.jar:?]
        at com.bekvon.bukkit.residence.Residence.reloadPlugin(Residence.java:326) [residence.jar:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:52) [residence.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:669) [patched_1.12.jar:git-Paper-1133]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:461) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1133]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1133]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException```

**Comment by Zrips** [comment]
Fixing
