### ISSUE TITLE
Residences cannot start

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#690]
Hi, when these values are true, then residence cannot start even when I don't have LWC plugin.
```
  Lwc:
    # Removes lwc protection from all defined objects when removing residence
    OnDelete: false
    # Removes lwc protection from all defined objects when buying residence
    OnBuy: false
    # Removes lwc protection from all defined objects when unrenting residence
    OnUnrent: false
```

```
[13:55:22] [Server thread/ERROR]: Error occurred while enabling Residence v4.9.3.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/griefcraft/lwc/LWC
	at com.bekvon.bukkit.residence.protection.ResidenceManager.removeLwcFromResidence(ResidenceManager.java:626) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.removeResidence(ResidenceManager.java:579) ~[?:?]
	at com.bekvon.bukkit.residence.utils.FileCleanUp.cleanFiles(FileCleanUp.java:75) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:667) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: com.griefcraft.lwc.LWC
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Tuinity-"9ac33d1"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	... 14 more
```

**Comment by Zrips** [comment]
8b47baf19af11cc76b4c0f9108387694fb5d5340
