### ISSUE TITLE
ResidenceChangedEvent error

### ISSUE THREAD

**Issue by Dzeivi** [Zrips/Residence#693]
I'm using latest version of Residence 4.9.3.3 and paper-1.16.5-558

`[11:58:47] [Server thread/ERROR]: Could not pass event ResidenceChangedEvent to Residence v4.9.3.3
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener1_9.onResidenceChange(ResidencePlayerListener1_9.java:68) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor346.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-558]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-558]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-558]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-558]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.handleNewLocation(ResidencePlayerListener.java:2166) ~[?:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerMove(ResidencePlayerListener.java:2002) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor377.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-558]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-558]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-558]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1409) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-558]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by DJIronic** [comment]
Same issue,

**Comment by rapofil** [comment]
Same issue

**Comment by StraikerinaCZ** [comment]
https://github.com/Zrips/Residence/blob/master/src/com/bekvon/bukkit/residence/listeners/ResidencePlayerListener1_9.java#L68
This checker should solve the problem:
`if(newRes == null || newRes...)`

**Comment by Zrips** [comment]
Fixed in Residence4.9.3.4
