### ISSUE TITLE
Residence 4.9.3.7+ cannot save residence NPE Error

### ISSUE THREAD

**Issue by In77** [Zrips/Residence#724]
![image](https://user-images.githubusercontent.com/44344308/120063980-8bee1800-c09c-11eb-872f-8564d23dc01e.png)

Residence 4.9.3.7 keeping NPE error on console. (See image)

Plugin Version: Residence 4.9.3.7
Server Version: Paper 1.16.5 build 743
Java & OS: Java 16, Debian 10

**Comment by In77** [comment]
![image](https://user-images.githubusercontent.com/44344308/120102650-9aacfb80-c17e-11eb-9bec-bf435571f0a9.png)
Still cannot save residence on 4.9.3.9

[19:37:41 INFO]: [Residence] Failed to save residence (mdcs)!
[19:37:41 ERROR]: [com.bekvon.bukkit.residence.protection.ResidenceManager] null
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "this.ownerUUID" is null
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.save(ResidencePermissions.java:678) ~[?:?]
        at com.bekvon.bukkit.residence.protection.ClaimedResidence.save(ClaimedResidence.java:1589) ~[?:?]
        at com.bekvon.bukkit.residence.protection.ResidenceManager.save(ResidenceManager.java:834) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.saveYml(Residence.java:1240) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:415) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:901) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1177) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[Paper-1.16.5-b748.jar:git-Paper-748]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by 4L0N50asd** [comment]
Getting a similar error using Residence 4.9.3.9 on every save

https://pastebin.com/raw/HcDskQ1B

**Comment by Zrips** [comment]
Cause was determined and fixed, please update to Residence4.9.3.10 version
