### ISSUE TITLE
It often reports errors.spaming in the console.paper1.14.4 4.9.3

### ISSUE THREAD

**Issue by coaststory** [Zrips/Residence#767]
13:59:45 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.PacketPlayOutWorldParticles.<init>(net.minecraft.server.v1_14_R1.ParticleParam, boolean, double, double, double, float, float, float, float, int)
[13:59:45 WARN]: at java.lang.Class.getConstructor0(Unknown Source)
[13:59:45 WARN]: at java.lang.Class.getConstructor(Unknown Source)
[13:59:45 WARN]: at net.Zrips.CMILib.Reflections.playEffect(Reflections.java:1723)
[13:59:45 WARN]: at com.bekvon.bukkit.residence.selection.SelectionManager.showParticles(SelectionManager.java:857)
[13:59:45 WARN]: at com.bekvon.bukkit.residence.selection.SelectionManager.access$2(SelectionManager.java:834)
[13:59:45 WARN]: at com.bekvon.bukkit.residence.selection.SelectionManager$2.run(SelectionManager.java:792)
[13:59:45 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[13:59:45 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:59:45 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:59:45 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:59:45 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:59:45 WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by Zrips** [comment]
Will be fixed with next CMILib update, you will need to update plugin to latest version with requires CMILib to avoid this issue.
Side note, you have really rare version of minecraft here which makes like 0.7% of entire player base, you might want to consider updating it to something more popular and more supported.
