### ISSUE TITLE
pl3xmap

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#777]
Hi, in the previous version you added pl3xmap support, but even if I turned it on, not all regions are displayed.
![image](https://user-images.githubusercontent.com/29830635/129439084-31c4d557-7084-4836-9194-1d62093c0ec8.png)
![image](https://user-images.githubusercontent.com/29830635/129439090-e887279b-32bb-47e3-934a-fd27d5c138b3.png)
![image](https://user-images.githubusercontent.com/29830635/129470279-89d38314-c692-47f3-b99c-3e79f4236278.png)
![image](https://user-images.githubusercontent.com/29830635/129470294-5f26b897-1cac-44e3-bd06-eba4379019ac.png)
http://82.208.17.82:29368/map.html
```Pl3xMap:
  # Enables or disable Pl3xMap Support
  Use: true
  # When set to true we will hide residence areas by default on Pl3xMap window
  # Residences can still be enabled throw provided Pl3xMap option on left top side
  HideByDefault: false
  # Shows or hides residence flags
  ShowFlags: true
  # When enabled default flags will not be included in residence overview
  ExcludeDefaultFlags: true
  # If set true, residence with hidden flag set to true will be hidden from Pl3xMap
  HideHidden: true
  Layer:
    # How deep to go into subzones to show
    SubZoneDepth: 2
  Border:
    # Color of border. Pick color from this page http://www.w3schools.com/colors/colors_picker.asp
    Color: '#FF0000'
    # Transparency. 0.3 means that only 30% of color will be visible
    Opacity: 0.3
    # Border thickness
    Weight: 3
  Fill:
    Opacity: 0.3
    Color: '#FF0000'
    ForRent: '#33cc33'
    Rented: '#99ff33'
    ForSale: '#0066ff'
  # Shows only regions on this list
  VisibleRegions: []
  # Hides region on map even if its not hidden in game
  HiddenRegions: []
```
```
[05:32:44] [Server thread/INFO]: [Residence] Pl3xMap residence activated!
[05:32:44] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.pl3x.map.api.MapWorld.layerRegistry()" because "<local5>" is null
[05:32:44] [Server thread/WARN]: at Residence5.0.0.2.jar//com.bekvon.bukkit.residence.pl3xmap.Pl3xMapManager.handleResidenceAdd(Pl3xMapManager.java:212)
[05:32:44] [Server thread/WARN]: at Residence5.0.0.2.jar//com.bekvon.bukkit.residence.pl3xmap.Pl3xMapManager.activate(Pl3xMapManager.java:329)
[05:32:44] [Server thread/WARN]: at Residence5.0.0.2.jar//com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:775)
[05:32:44] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:32:44] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:32:44] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[05:32:44] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529)
[05:32:44] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443)
[05:32:44] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712)
[05:32:44] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[05:32:44] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1201)
[05:32:44] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[05:32:44] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)

[05:33:21] [Server thread/WARN]: [Residence] Task #202 for Residence v5.0.0.2 generated an exception
java.lang.NullPointerException: Cannot invoke "net.pl3x.map.api.MapWorld.layerRegistry()" because "<local5>" is null
     at com.bekvon.bukkit.residence.pl3xmap.Pl3xMapManager.handleResidenceAdd(Pl3xMapManager.java:212) ~[Residence5.0.0.2.jar:?]
     at com.bekvon.bukkit.residence.pl3xmap.Pl3xMapManager.access$1(Pl3xMapManager.java:198) ~[Residence5.0.0.2.jar:?]
     at com.bekvon.bukkit.residence.pl3xmap.Pl3xMapManager$1.run(Pl3xMapManager.java:64) ~[Residence5.0.0.2.jar:?]
     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1331]
     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1331]
     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1331]
     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1331]
     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1331]
     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1331]
     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1331]
     at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Zrips** [comment]
7a0a1edfcf74a28e2fc3881518ebe6d4af639164
