### ISSUE TITLE
Could not pass event PortalCreateEvent to Residence v5.0.0.4

### ISSUE THREAD

**Issue by TenkyuChimata** [Zrips/Residence#807]
Server: Paper 1.17.1-353
```
[00:46:01] [Server thread/ERROR]: Could not pass event PortalCreateEvent to Residence v5.0.0.4
java.lang.NullPointerException: Cannot invoke "com.bekvon.bukkit.residence.protection.ClaimedResidence.getPermissions()" because "res" is null
	at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.onBlockBurn(ResidenceBlockListener.java:1039) ~[Residence.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor190.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-353]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-353]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-353]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.world.level.portal.PortalForcer.createPortal(PortalForcer.java:218) ~[app:?]
	at net.minecraft.server.level.ServerPlayer.findOrCreatePortal(ServerPlayer.java:1198) ~[app:?]
	at net.minecraft.world.entity.Entity.findDimensionEntryPoint(Entity.java:3281) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.server.level.ServerPlayer.findDimensionEntryPoint(ServerPlayer.java:1023) ~[app:?]
	at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1076) ~[app:?]
	at net.minecraft.world.entity.Entity.handleNetherPortal(Entity.java:2723) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:724) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:392) ~[app:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:699) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2853) ~[app:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:270) ~[app:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:671) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:316) ~[app:?]
	at net.minecraft.network.Connection.tick(Connection.java:555) ~[app:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[app:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1653) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-353]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-353]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Zrips** [comment]
fc9c40f07a293140a52b6c97541e7391ecbc1027
