### ISSUE TITLE
1.18 - Error when going to nether/back

### ISSUE THREAD

**Issue by corwinbass** [Zrips/Residence#818]
upon entering nether portal, exception is raised in console
new portal is created every time player goes thru one, both ways

Residence 5.0.0.4
CMILib 1.1.0.0
server is running Paper version git-Paper-32 (MC: 1.18)

exception:
` [14:01:49 ERROR]: Could not pass event PortalCreateEvent to Residence v5.0.0.4
java.lang.NullPointerException: Cannot invoke "com.bekvon.bukkit.residence.protection.ClaimedResidence.getPermissions()" because "res" is null
at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.onBlockBurn(ResidenceBlockListener.java:1039) ~[Residence.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor732.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-32]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.level.portal.PortalForcer.createPortal(PortalForcer.java:220) ~[?:?]
at net.minecraft.server.level.ServerPlayer.getExitPortal(ServerPlayer.java:1225) ~[?:?]
at net.minecraft.world.entity.Entity.findDimensionEntryPoint(Entity.java:3207) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.server.level.ServerPlayer.findDimensionEntryPoint(ServerPlayer.java:1052) ~[?:?]
at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1105) ~[?:?]
at net.minecraft.world.entity.Entity.handleNetherPortal(Entity.java:2647) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.world.entity.Entity.baseTick(Entity.java:729) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:389) ~[?:?]
at net.minecraft.world.entity.Entity.tick(Entity.java:703) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2853) ~[?:?]
at net.minecraft.world.entity.player.Player.tick(Player.java:268) ~[?:?]
at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:669) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:315) ~[?:?]
at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-32]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-32]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Zrips** [comment]
fc9c40f07a293140a52b6c97541e7391ecbc1027
