### ISSUE TITLE
Error with randomTp

### ISSUE THREAD

**Issue by MikuSnow** [Zrips/Residence#836]
command: /res rt
error:
```
[00:54:14 WARN]: java.lang.IllegalStateException: Asynchronous chunk load!
[00:54:14 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[00:54:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:267)
[00:54:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:162)
[00:54:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:104)
[00:54:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:576)
[00:54:14 WARN]:        at com.bekvon.bukkit.residence.utils.RandomTp.getDownLocationSimple(RandomTp.java:278)
[00:54:14 WARN]:        at com.bekvon.bukkit.residence.utils.RandomTp.get(RandomTp.java:204)
[00:54:14 WARN]:        at com.bekvon.bukkit.residence.utils.RandomTp.lambda$0(RandomTp.java:148)
[00:54:14 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[00:54:14 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
[00:54:14 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[00:54:14 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[00:54:14 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[00:54:14 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by Zrips** [comment]
74ced3933db8458f93001f6fb3d52ab9f906c193
