### ISSUE TITLE
Asynchronous entity world add and crash servers

### ISSUE THREAD

**Issue by caoli5288** [Zrips/Residence#839]
Console will spawn this message and crash for while.

```
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: java.lang.IllegalStateException: Asynchronous entity world add!
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.minecraft.server.v1_8_R3.World.b(World.java:3028)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:985)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:18)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:17)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:162)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:150)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.AsyncChunksSync.getChunkAtAsync(AsyncChunksSync.java:12)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.Environment.getChunkAtAsync(Environment.java:34)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.PaperLib.getChunkAtAsync(PaperLib.java:59)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.PaperLib.getChunkAtAsync(PaperLib.java:49)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at com.bekvon.bukkit.residence.utils.RandomTp.getDownLocationSimple(RandomTp.java:269)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at com.bekvon.bukkit.residence.utils.RandomTp.get(RandomTp.java:204)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at com.bekvon.bukkit.residence.utils.RandomTp.lambda$0(RandomTp.java:148)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[09:30:30] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/18/22, 10:33 AM
Description: Exception ticking world entities

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at com.google.common.collect.Iterators$5.next(Iterators.java:553)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1733)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:862)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Zrips** [comment]
Should be resolved with latest versions
