### ISSUE TITLE
v4.7.1.1 with latest Spigot 1.12 build fails to startup

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#84]
It tries to enable Residence, fails and then shuts the JVM down.  v4.7.0.5 works fine.

[21:44:37] [Server thread/INFO]: [Residence] Enabling Residence v4.7.1.1
[21:44:37] [Server thread/INFO]: [Residence] Disabling Residence v4.7.1.1
[21:44:37] [Server thread/ERROR]: Error occurred while disabling Residence v4.7.1.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:339) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:749) [Residence4.7.1.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[21:44:37] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m - FAILED INITIALIZATION! DISABLED! ERROR:[m
[21:44:37] [Server thread/ERROR]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:563) ~[Residence4.7.1.1.jar:?]
	at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:254) ~[Residence4.7.1.1.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:429) [Residence4.7.1.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[21:44:37] [Server thread/ERROR]: Error occurred while enabling Residence v4.7.1.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:755) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-b1b9ab0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[21:44:37] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.0.1-b499

**Comment by DaDMaR** [comment]
Got the same error as above - moved from 4.7.0.5 -> 4.7.1.1, now switching to 4.7.1.0 - and checking

**Comment by D3thw0lf** [comment]
Got the same but making a clean start (removing config etc. from Residence, make sure to create a backup) worked.

**Comment by Zrips** [comment]
Will be fixed
