### ISSUE TITLE
Slimefun dough residence error

### ISSUE THREAD

**Issue by DaliborTrampota** [Zrips/Residence#845]
Hello, I was redirected here https://github.com/baked-libs/dough/issues/128

Ancient altar from SlimeFun does not work with residence.
https://pastebin.com/5HEa19Ab
this is the error that is send every second into the console

Server Software: This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
Minecraft Version: 1.18.1

plugins:
AdvancedPortals, ajParkour, ArmorStandTools, AuctionHouse, AuthMe, bAnnouncer*, BlockParticles, ClickSort, CMILib, CoreProtect, dynmap, Dynmap-WorldGuard*, DynMap_Residence, EpicReplant, Essentials, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExoticGarden, ExtraGear, FakaHedaMinequery, FluffyMachines, GMusic, GSit, HolographicDisplays, InventoryRollbackPlus, Jobs, JumpPads, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MyCommand, MythicMobs, PlaceholderAPI, PlayTime*, PrivateStorage, ProtocolLib, Residence, SignShop, SkinsRestorer, sleep-most, Slimefun, SoulJars, TAB, TNTRun_reloaded, UberEnchant, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldSpawn*

**Comment by StraikerinaCZ** [comment]
I can confirm this bug on plugin version 5.0.1.1

**Comment by DaliborTrampota** [comment]
Any update?

**Comment by DaliborTrampota** [comment]
https://pastebin.com/iw1sL7PS

this log is from 5.0.1.1 the above was from 5.0.1.0

**Comment by Ashiroo** [comment]
i have same problem

**Comment by WongIong** [comment]
same here, any progress?

**Comment by DaliborTrampota** [comment]
@Zrips please any feedback? my console is flooded by the errors

**Comment by DaliborTrampota** [comment]
rip

**Comment by Dreeam-qwq** [comment]
Residence 5.0.1.1
Slimefun4 - DEV 999 (git e02ee)


```
[02:42:45 WARN]: [Residence] Task #27 for Residence v5.0.1.1 generated an exception
java.lang.NoSuchMethodError: io/github/thebusybiscuit/slimefun4/libraries/dough/protection/ProtectionManager.registerModule(Lorg/bukkit/Server;Ljava/lang/String;Ljava/util/function/Function;)V (loaded from file:/D:/server/Winds/Astatine/plugins/Slimefun4%20-%20DEV%20999%20(git%20e02ee).jar by PluginClassLoader{plugin=Slimefun vDEV - 999 (git e02eedd9), pluginEnabled=true, url=plugins\Slimefun4 - DEV 999 (git e02ee).jar}) called from class com.bekvon.bukkit.residence.slimeFun.SlimefunManager (loaded from file:/D:/server/Winds/Astatine/plugins/%5B领地%5DResidence5.0.1.1.jar by PluginClassLoader{plugin=Residence v5.0.1.1, pluginEnabled=true, url=plugins\[领地]Residence5.0.1.1.jar}).
        at com.bekvon.bukkit.residence.slimeFun.SlimefunManager.lambda$0(SlimefunManager.java:23) ~[[领地]Residence5.0.1.1.jar:?]
        at com.bekvon.bukkit.residence.slimeFun.SlimefunManager$$Lambda$5293/0x00000000dfafb300.accept(Unknown Source) ~[[领地]Residence5.0.1.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[mirai-1.18.1.jar:git-Mirai-"415fde5"]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[mirai-1.18.1.jar:git-Mirai-"415fde5"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[mirai-1.18.1.jar:git-Mirai-"415fde5"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[mirai-1.18.1.jar:git-Mirai-"415fde5"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1487) ~[mirai-1.18.1.jar:git-Mirai-"415fde5"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1276) ~[mirai-1.18.1.jar:git-Mirai-"415fde5"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[mirai-1.18.1.jar:git-Mirai-"415fde5"]
        at net.minecraft.server.MinecraftServer$$Lambda$4055/0x00000000ddea3dc0.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by misuda12** [comment]
Just dont use DEV versions of slimefun use official release instead https://github.com/Slimefun/Slimefun4/releases/tag/RC-30
However for those who wants to build it on your own all you need to do is change

`
manager.registerModule(Bukkit.getServer(), "Residence", plugin -> new SlimeFunResidenceModule(plugin));
`
to
`
manager.registerModule(Bukkit.getServer().getPluginManager(), "Residence", plugin -> new SlimeFunResidenceModule(plugin));
`

**Comment by Zrips** [comment]
177366d487f47c10a0ed131a3c4f56c557dbb6d1
