### ISSUE TITLE
 java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getBlocks()L

### ISSUE THREAD

**Issue by mrcang09** [Zrips/Residence#850]
[16:03:09] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getBlocks()Ljava/util/List;
[16:03:09] [Server thread/WARN]: 	at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.onBlockBurn(ResidenceBlockListener.java:1017)
[16:03:09] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor771.execute(Unknown Source)
[16:03:09] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[16:03:09] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[16:03:09] [Server thread/WARN]: 	at pw.yumc.Yum.inject.ListenerInjector.execute(ListenerInjector.java:87)
[16:03:09] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:03:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.BlockPortal$Shape.createPortal(BlockPortal.java:377)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.BlockPortal.b(BlockPortal.java:78)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.BlockFire.onPlace(BlockFire.java:330)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:277)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[16:03:09] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:03:09] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[16:03:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[16:03:09] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

Sever:paperspigot1.12.2

**Comment by Zrips** [comment]
2cd25c8214d721577d405140b0d8e06ff680910e
