### ISSUE TITLE
Installation failed while loading

### ISSUE THREAD

**Issue by kioging** [Zrips/Residence#886]
When I opened the server of 1.12.2, an error occurred in the plugin.

Minecraft Version : 1.12.2
Java Version : 8(1.8.0_311)
Residence Version : 5.0.1.6
WorldEdit Version : 6.1.9
LuckPerms Version : 5.4.9

Console Informations :

[00:00:00] [Server thread/INFO]: [Residence] Enabling Residence v5.0.1.6
[00:00:00] [Server thread/INFO]: [Residence] Wrote default flags...
[00:00:00] [Server thread/INFO]: [Residence] Disabling Residence v5.0.1.6
[00:00:00] [Server thread/INFO]: [Residence] Loaded (2) groups
[00:00:00] [Server thread/INFO]: [Residence] Found Vault using permissions plugin:LuckPerms
[00:00:00] [Server thread/INFO]: [Residence] Found WorldEdit 6.1.9;caf0ad9
[00:00:00] [Server thread/INFO]: [Residence] - FAILED INITIALIZATION! DISABLED! ERROR:
[00:00:00] [Server thread/ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:62) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:492) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper_1.12.2_1620.jar:git-Paper-1620]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
[00:00:01] [Server thread/INFO]: Done (34.932s)! For help, type "help" or "?"
[00:00:01] [Server thread/INFO]: Stopping server

**Comment by SickProdigy** [comment]
CMIlib missing or forgot to list version?

**Comment by Zrips** [comment]
cd353dcecc457bb0d1a52f377f9ae6ae93df0318
