### ISSUE TITLE
support 1.19

### ISSUE THREAD

**Issue by RanWhite** [Zrips/Residence#894]

**Comment by SickProdigy** [comment]
Update cmilib, https://www.zrips.net/cmilib/

**Comment by PetyXbron** [comment]
I have the newest version (1.2.0.1) and it still doesn't work. At the start of 1.18, we needed to wait too because of the new coordinates height limits. I think the Residence plugin needs to be updated independently.

**Comment by SickProdigy** [comment]
> I have the newest version (1.2.0.1) and it still doesn't work. At the start of 1.18, we needed to wait too because of the new coordinates height limits. I think the Residence plugin needs to be updated independently.

Hello, we are on 1.19 now.
Make sure there is no older version of cmilib left behind in your plugins folder.
Without any details of your setup, I can only assume here.

Things needed that would make this go a lot smoother:
Minecraft version: ie spigot 1.19
Cmilib version: 
Residence version: 

Please don't say "i have the newest version", just state which versions. It's counterproductive for the people trying to help you.

If you checkout the discord, cmilib is the only thing that needs updated
https://i.imgur.com/ImSMfML.png

**Comment by exit151** [comment]
Okay, I'll bite..

Minecraft Version:  Spigot 1.19 (can't get the build because it crashes, but literally build 10 minutes ago, and failed on every 1.19 build since it's release)
CMILib: 1.2.0.2 (also failed with 1.2.0.1)
Residence Version:  5.0.1.6

Here's the pertinent log:

`[15:05:50] [Server thread/INFO]: [Residence] Enabling Residence v5.0.1.6
[15:05:50] [Server thread/INFO]: [Residence] Disabling Residence v5.0.1.6
[15:05:50] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded (3) groups[m
[15:05:50] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found Vault using permissions plugin:bPermissions2[m
[15:05:50] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found WorldEdit 7.2.10+1742f98[m
[15:05:50] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m - FAILED INITIALIZATION! DISABLED! ERROR:[m
[15:05:50] [Server thread/ERROR]: null
java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Items.CMIItemStack.getCMIType()" because the return value of "net.Zrips.CMILib.Items.ItemManager.getItem(String, net.Zrips.CMILib.Items.CMIAsyncHead)" is null
	at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:62) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:492) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:05:50] [Server thread/ERROR]: Error occurred while enabling Residence v5.0.1.6 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.getShopSignUtilManager(Residence.java:997) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:836) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by fcernese** [comment]
Running Paper version git-Paper-34 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e52499e)
[CMILib] Enabling CMILib v1.2.0.2

[13:52:59 ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Items.CMIItemStack.getCMIType()" because the return value of "net.Zrips.CMILib.Items.ItemManager.getItem(String, net.Zrips.CMILib.Items.CMIAsyncHead)" is null
        at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:62) ~[Residence5.0.1.6.jar:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:492) ~[Residence5.0.1.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-34]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-34]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:52:59 ERROR]: Error occurred while enabling Residence v5.0.1.6 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.getShopSignUtilManager(Residence.java:997) ~[Residence5.0.1.6.jar:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:836) ~[Residence5.0.1.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-34]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-34]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-34]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
