### ISSUE TITLE
[Error] Residence & Signshop

### ISSUE THREAD

**Issue by NelsonHD** [Zrips/Residence#90]
I got the error report when my server tps down to 2.
Spigot 1.8.8
Residence v 4.7.0.5
SignShop v.2.11.2
`[11:58:13]` [Server thread/ERROR]: Could not pass event SSLinkEvent to SignShop v2.11.2
org.bukkit.event.EventException
	at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:79) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.wargamer2010.signshop.SignShop.scheduleEvent(SignShop.java:169) [SignShop.jar:?]
	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:456) [SignShop.jar:?]
	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:443) [SignShop.jar:?]
	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:438) [SignShop.jar:?]
	at org.wargamer2010.signshop.listeners.SignShopPlayerListener.onPlayerInteract(SignShopPlayerListener.java:230) [SignShop.jar:?]
	at sun.reflect.GeneratedMethodAccessor231.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:69) [MassiveLag.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IncompatibleClassChangeError: Expected static method com.bekvon.bukkit.residence.Residence.getResidenceManager()Lcom/bekvon/bukkit/residence/protection/ResidenceManager;
	at org.wargamer2010.signshop.hooks.ResidenceHook.canBuild(ResidenceHook.java:19) ~[?:?]
	at org.wargamer2010.signshop.hooks.HookManager.canBuild(HookManager.java:51) ~[?:?]
	at org.wargamer2010.signshop.listeners.sslisteners.SimpleBlockProtector.onSSLinkEvent(SimpleBlockProtector.java:17) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1114.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:69) ~[?:?]
	... 30 more`
Also, if the chest did not lock by Lockette or other plugin, player can steal item from shop, can add a support for hook signshop ?　Thx a lot　:)

**Comment by Zrips** [comment]
Signshop has to update their hook into Residence, inform his dev about this. There was changes related to that quite some time ago.
And support like this should be done from Signshop side as those chests are being used by that particular plugin and Residence plugin is not related to that directly.
