### ISSUE TITLE
Running on catserver 1.12.2 will crash. It may be a problem with the Java version, but it only supports java11 at most

### ISSUE THREAD

**Issue by 2495904552** [Zrips/Residence#901]
[09:57:33] [Server thread/ERROR] [com.bekvon.bukkit.residence.Residence]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:62) ~[Residence5.0.1.6.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:492) [Residence5.0.1.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [JavaPlugin.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-6eb82ffe]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:57:33] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Residence v5.0.1.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/bekvon/bukkit/residence/shopStuff/ShopSignUtil
	at com.bekvon.bukkit.residence.Residence.getShopSignUtilManager(Residence.java:997) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:836) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-6eb82ffe]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.bekvon.bukkit.residence.shopStuff.ShopSignUtil
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:141) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.bekvon.bukkit.residence.shopStuff.ShopSignUtil
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 11 more

**Comment by Zrips** [comment]
cd353dcecc457bb0d1a52f377f9ae6ae93df0318
