### ISSUE TITLE
Loading datas into memory is TOO SLOW. How can I restore it(v5.0.1.3) to the old version(v4.8.6.6) and load data like that?

### ISSUE THREAD

**Issue by Yingz520** [Zrips/Residence#902]
[00:00:31] [Server thread/INFO]: [Residence] Found Vault using economy system: SaneEconomy
[00:14:43] [Server thread/INFO]: [Residence] Loaded world data into memory. (851.99 sec) -> 815 residences

It cost 14mins to load the datas. IT IS TOO SLOW!!! How can I restore it(v5.0.1.3) to the old version(v4.8.6.6) and load data like that?

**Comment by Zrips** [comment]
This should not happen in normal conditions. As an example of 23503 residences being loaded in, takes 497ms
![image](https://user-images.githubusercontent.com/10416201/177969009-c315e351-f014-471d-9f27-7f79a318d433.png)
Can you send me your residence save file for testing over discord? As something is wrong here and needs to be looked at.

**Comment by Yingz520** [comment]
How can I send you the file over discord? I seldom use discord. After you tell me how to send the file, I will send you the file as soon that you can check it.

**Comment by Zrips** [comment]
At discord you can find we by Zrips#9691 name, there are general discord links on Residence plugin page, so you can use that. Or you can upload your file somewhere and share your link. Discord would be better option as it will be more private and you wont need to share your files on a public place.

**Comment by Yingz520** [comment]
When I try using discord to find you, it displayed that "Friend requests are currently not accepted. They need to actively add you as a friend". And I can't find your link on Residence plugin page on spigot. Relatively, you can download the file under this link.(In order to protect privacy, I set the link to be destroyed after downloading once and only valid within 24 hours.) Thx. [https://airportal.cn/922575/J9KXY9yfSD](url)

**Comment by Zrips** [comment]
![image](https://user-images.githubusercontent.com/10416201/178003194-5cbe1326-bb98-4267-add0-7c1b44e9540c.png)
So its interesting what exactly is going on in your situation as it loads for me in 127ms

**Comment by Zrips** [comment]
Try using latest builds 5.0.1.6 as there have been some improvements relating to initial loading times. This could help out.
And dont be afraid to use new save mechanics which can improve that load and save by quite a bit, while minimizing save file too. Like in your example, your original file contains over 83 000 lines of information, new save method compacts it into 34 000. Tho this is side thing and wont really resolve your loading times, but updating your plugin version to latest one should improve those times.

**Comment by Yingz520** [comment]
Okey. I will update the version to 5.0.1.6 later. Thank you for your patience.

**Comment by Yingz520** [comment]
[13:45:03] [Server thread/INFO]: [Residence] - FAILED INITIALIZATION! DISABLED! ERROR:
[13:45:03] [Server thread/ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:62) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:492) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[13:45:03] [Server thread/ERROR]: Error occurred while enabling Residence v5.0.1.6 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.shopStuff.ShopSignUtil.LoadShopVotes(ShopSignUtil.java:135) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:836) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-cj22-1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by Yingz520** [comment]
What's the matter about the error msg?

**Comment by Zrips** [comment]
Its fixed in latest commits, for temporary fix from your end, you will need to chance materials for flags for GUI to something else what actually exists in 1.12 version.

**Comment by Yingz520** [comment]
What exactly should I do?

**Comment by Zrips** [comment]
Download this version and you should be good to go [](https://zrips.net/Residence/download.php?file=Residence5.0.1.7.jar)

**Comment by Yingz520** [comment]
ok i will try it later!

**Comment by Yingz520** [comment]
![image](https://user-images.githubusercontent.com/35760226/178111940-8060c745-2122-46f2-9df1-a06c45629721.png)
It seems to work! I believe it should be the same in the future. Thank you so much!
