### ISSUE TITLE
onCommand ConcurrentModificationException

### ISSUE THREAD

**Issue by Rukes** [Zrips/Residence#91]
```
java.util.ConcurrentModificationException: [Residence] Plugin Residence v4.7.1.2 generated an exception while executing task 208781
    at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
    at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247)
    at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242)
    at com.bekvon.bukkit.residence.protection.ResidenceManager.save(ResidenceManager.java:801)
    at com.bekvon.bukkit.residence.Residence.saveYml(Residence.java:1086)
    at com.bekvon.bukkit.residence.Residence.access$0(Residence.java:1081)
    at com.bekvon.bukkit.residence.Residence$6$1.run(Residence.java:311)
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zrips** [comment]
Should be fixed with next build
