### ISSUE TITLE
Slimefun plugin adaptation issues

### ISSUE THREAD

**Issue by NakiriAyamesuki** [Zrips/Residence#917]
Minecraft Version:1.18.2
Server: 1.18.2 PpaperSpigot-386
Residence Version: v5.0.1.7
Slimefun: v2022.07

Config.yml:
    UUIDConvertion: true
    OfflineMode: true

[18:40:45 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.0.1.7"
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "player" is null
        at com.bekvon.bukkit.residence.protection.FlagPermissions.getPlayerFlags(FlagPermissions.java:333) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.FlagPermissions.playerCheck(FlagPermissions.java:564) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.FlagPermissions.playerHas(FlagPermissions.java:512) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:127) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:46) ~[Residence5.0.1.7.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:167) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkVanillaGrabber.tryGrabItem(NetworkVanillaGrabber.java:90) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkVanillaGrabber.onTick(NetworkVanillaGrabber.java:59) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:100) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170) ~[Slimefun-v2022.07-release.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:40:45 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.0.1.7"
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "player" is null
        at com.bekvon.bukkit.residence.protection.FlagPermissions.getPlayerFlags(FlagPermissions.java:333) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.FlagPermissions.playerCheck(FlagPermissions.java:564) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.FlagPermissions.playerHas(FlagPermissions.java:512) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:127) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:46) ~[Residence5.0.1.7.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:167) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkVanillaGrabber.tryGrabItem(NetworkVanillaGrabber.java:90) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkVanillaGrabber.onTick(NetworkVanillaGrabber.java:59) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:100) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170) ~[Slimefun-v2022.07-release.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

[18:51:44 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.0.1.7"
java.lang.NullPointerException: null
[18:51:44 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.0.1.7"
java.lang.NullPointerException: null
[18:51:44 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.0.1.7"
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "player" is null
        at com.bekvon.bukkit.residence.protection.FlagPermissions.getPlayerFlags(FlagPermissions.java:333) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.FlagPermissions.playerCheck(FlagPermissions.java:564) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.FlagPermissions.playerHas(FlagPermissions.java:512) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:127) ~[Residence5.0.1.7.jar:?]
        at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:46) ~[Residence5.0.1.7.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:167) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkVanillaPusher.tryPushItem(NetworkVanillaPusher.java:82) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkVanillaPusher.onTick(NetworkVanillaPusher.java:58) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:100) ~[SlimefunNetworks-Build 63 zh-CN(ybw0014) (git 0680fed).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189) ~[Slimefun-v2022.07-release.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170) ~[Slimefun-v2022.07-release.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Zrips** [comment]
f80034c444e97e419cd6eefc2da10755f9211cfa
