### ISSUE TITLE
Players can put buckets in unauthorized territories

### ISSUE THREAD

**Issue by polang233** [Zrips/Residence#958]
**1.12.2 Paper** 
Java environment **jdk8**
plugin virsion **Residence5.1.0.0   CMILib1.2.3.7**

**Players can place buckets without permission, and the following errors are reported**
This problem has existed since 5.0.1.5
> 
> [18:53:42] [Server thread/ERROR]: Could not pass event PlayerBucketEmptyEvent to Residence v5.1.0.0
> java.lang.NoSuchMethodError: org.bukkit.block.BlockFace.getDirection()Lorgkkit/util/Vector;
> 	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerBucketEmpty(ResidencePlayerListener.java:1786) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor79.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:187) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:160) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.ItemBucket.a(ItemBucket.java:130) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.ItemBucket.a(ItemBucket.java:76) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.ItemStack.a(ItemStack.java:330) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:431) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1064) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_333]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_333]
> 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
> 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]

**Comment by acsoto** [comment]
I have the same problem, same env: Residence 5.1.0.0 CMILib1.2.3.7 Paper 1.12.2

**Comment by polang233** [comment]
> I have the same problem, same env: Residence 5.1.0.0 CMILib1.2.3.7 Paper 1.12.2

![L59`Z30}V%BR9L$68EO7W_5](https://user-images.githubusercontent.com/104189797/204074384-d0413410-efac-4f7b-b715-3c234d4a6556.jpg)
There is no such class in 1.12.2. The problem is version compatibility.
Can only wait for the author to repair

**Comment by acsoto** [comment]
Thanks for replying. This is a serious problem to be solved. My players put water and lava all over the place. I wish that the author can view our problem.

**Comment by acsoto** [comment]
How do you manage this now? I'm wondering if I can switch to old version.

**Comment by polang233** [comment]
> How do you manage this now? I'm wondering if I can switch to old version.

You can try to reduce the version to 5.0.1.5, which at least solves the problem

**Comment by polang233** [comment]
> How do you manage this now? I'm wondering if I can switch to old version.

啊？你是中国人啊   早说嘛 省的用翻译

**Comment by acsoto** [comment]
OK，感谢😄
