### ISSUE TITLE
1.19.3 NPE

### ISSUE THREAD

**Issue by SlimeDog** [Zrips/Residence#971]
Paper 1.19.3-323
CMILib 1.2.4.0
Residence 5.1.0.1

On server start-up
```
[07:26:35] [Server thread/INFO]: [Residence] Enabling Residence v5.1.0.1
[07:26:35] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.MobSpawnerData.a()" because "net.minecraft.world.level.block.entity.TileEntityMobSpawner.d().f" is null
[07:26:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R2.block.CraftCreatureSpawner.getSpawnedType(CraftCreatureSpawner.java:18)
[07:26:35] [Server thread/WARN]:        at CMILib-1.2.4.0.jar//net.Zrips.CMILib.Items.CMIItemStack.getEntityType(CMIItemStack.java:601)
[07:26:35] [Server thread/WARN]:        at CMILib-1.2.4.0.jar//net.Zrips.CMILib.Items.CMIItemStack.setEnt(CMIItemStack.java:363)
[07:26:35] [Server thread/WARN]:        at CMILib-1.2.4.0.jar//net.Zrips.CMILib.Items.CMIItemStack.getItemStack(CMIItemStack.java:385)
[07:26:35] [Server thread/WARN]:        at Residence-5.1.0.1.jar//com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:68)
[07:26:35] [Server thread/WARN]:        at Residence-5.1.0.1.jar//com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:494)
[07:26:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:26:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[07:26:35] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[07:26:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[07:26:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[07:26:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[07:26:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[07:26:35] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[07:26:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[07:26:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[07:26:35] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
```
No NPE on Spigot 1.19.2-3610.

Residences load correctly in both environments, and are displayed in lists.

**Comment by Zrips** [comment]
You can ignore this error for time being, it wont effect plugins work. Its just something what needs to be sorted out from spigot/paper side at some point.

**Comment by SlimeDog** [comment]
OK.
