### ISSUE TITLE
Server shuts down when showing the error about residence

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#995]
I find that a lot of players try to run into a residence that does not allow players to move inside.
At the same time, a player is using command res expand.
I am not sure which of them is related to the issue.
And then, the server keep showing the error and shut down.

**The log before server crashes.**
[22:21:15] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to Residence v5.1.1.0
java.lang.StackOverflowError: null
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:693) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1325) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1232) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1227) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:551) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.teleport(ResidencePlayerListener.java:2251) ~[Residence5.1.1.0.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.handleNewLocation(ResidencePlayerListener.java:2517) ~[Residence5.1.1.0.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onPlayerTeleport(ResidencePlayerListener.java:1875) ~[Residence5.1.1.0.jar:?]

**Crash report**
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Could not initialize class com.destroystokyo.paper.event.server.ServerExceptionEvent
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:699)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674)
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29)
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Zrips** [comment]
55f240da65287c5e41032033e4ed6cbc7eed00cf
